-- Enums
CREATE TYPE org_role AS ENUM ('ORG_ADMIN', 'ORG_USER');
CREATE TYPE team_role AS ENUM ('TEAM_LEADER', 'CONTRIBUTOR');
CREATE TYPE task_status AS ENUM ('BACKLOG', 'TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE');
CREATE TYPE task_priority AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'URGENT');
CREATE TYPE resource_type AS ENUM ('HARDWARE', 'SOFTWARE', 'ROOM', 'OTHER');
CREATE TYPE resource_status AS ENUM ('AVAILABLE', 'BOOKED', 'MAINTENANCE');
CREATE TYPE booking_status AS ENUM ('CONFIRMED', 'CANCELLED', 'PENDING', 'CONFLICT');

-- Organization settings (1:1 with orgs)
CREATE TABLE organization_settings (
    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT organization_settings_pk PRIMARY KEY,

    org_id BIGINT NOT NULL
        CONSTRAINT organization_settings_org_id_unique UNIQUE
        CONSTRAINT organization_settings_org_id_fkey REFERENCES orgs (id),

    allow_cloud_llm BOOLEAN NOT NULL DEFAULT false,
    retention_days INT NOT NULL DEFAULT 30,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Users
CREATE TABLE users (
    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT users_pk PRIMARY KEY,

    org_id BIGINT NOT NULL
        CONSTRAINT users_org_id_fkey REFERENCES orgs (id),

    active BOOLEAN NOT NULL DEFAULT true,
    email VARCHAR(255) NOT NULL
        CONSTRAINT users_email_unique UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    avatar_url VARCHAR(512),
    org_role org_role NOT NULL DEFAULT 'ORG_USER',
    last_active_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX users_org_id_idx ON users (org_id);

-- Teams
CREATE TABLE teams (
    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT teams_pk PRIMARY KEY,

    public_id UUID NOT NULL DEFAULT gen_random_uuid()
        CONSTRAINT teams_public_id_unique UNIQUE,

    org_id BIGINT NOT NULL
        CONSTRAINT teams_org_id_fkey REFERENCES orgs (id),

    name VARCHAR(255) NOT NULL,
    description TEXT,

    created_by_user BIGINT NOT NULL
        CONSTRAINT teams_created_by_user_fkey REFERENCES users (id),

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX teams_org_id_idx ON teams (org_id);

-- Team members
CREATE TABLE team_members (
    team_id BIGINT NOT NULL
        CONSTRAINT team_members_team_id_fkey REFERENCES teams (id),

    user_id BIGINT NOT NULL
        CONSTRAINT team_members_user_id_fkey REFERENCES users (id),

    role team_role NOT NULL DEFAULT 'CONTRIBUTOR',
    joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT team_members_pk PRIMARY KEY (team_id, user_id)
);

CREATE INDEX team_members_user_id_idx ON team_members (user_id);

-- Channels
CREATE TABLE channels (
    id UUID
        DEFAULT gen_random_uuid()
        CONSTRAINT channels_pk PRIMARY KEY,

    team_id BIGINT NOT NULL
        CONSTRAINT channels_team_id_fkey REFERENCES teams (id),

    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX channels_team_id_idx ON channels (team_id);

-- Chat messages
CREATE TABLE chat_messages (
    id UUID
        DEFAULT gen_random_uuid()
        CONSTRAINT chat_messages_pk PRIMARY KEY,

    channel_id UUID NOT NULL
        CONSTRAINT chat_messages_channel_id_fkey REFERENCES channels (id),

    sender_id BIGINT NOT NULL
        CONSTRAINT chat_messages_sender_id_fkey REFERENCES users (id),

    reply_to_id UUID
        CONSTRAINT chat_messages_reply_to_id_fkey REFERENCES chat_messages (id),

    message TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX chat_messages_channel_id_idx ON chat_messages (channel_id);
CREATE INDEX chat_messages_sender_id_idx ON chat_messages (sender_id);

-- Tasks
CREATE TABLE tasks (
    id UUID
        DEFAULT gen_random_uuid()
        CONSTRAINT tasks_pk PRIMARY KEY,

    team_id BIGINT NOT NULL
        CONSTRAINT tasks_team_id_fkey REFERENCES teams (id),

    reporter_id BIGINT NOT NULL
        CONSTRAINT tasks_reporter_id_fkey REFERENCES users (id),

    assignee_id BIGINT
        CONSTRAINT tasks_assignee_id_fkey REFERENCES users (id),

    source_message_id UUID
        CONSTRAINT tasks_source_message_id_fkey REFERENCES chat_messages (id),

    title VARCHAR(255) NOT NULL,
    description TEXT,
    status task_status NOT NULL DEFAULT 'BACKLOG',
    priority task_priority NOT NULL DEFAULT 'MEDIUM',
    due_date TIMESTAMPTZ,
    ai_generated BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX tasks_team_id_idx ON tasks (team_id);
CREATE INDEX tasks_assignee_id_idx ON tasks (assignee_id);
CREATE INDEX tasks_status_idx ON tasks (status);

-- Resources
CREATE TABLE resources (
    id UUID
        DEFAULT gen_random_uuid()
        CONSTRAINT resources_pk PRIMARY KEY,

    org_id BIGINT NOT NULL
        CONSTRAINT resources_org_id_fkey REFERENCES orgs (id),

    name VARCHAR(255) NOT NULL,
    type resource_type NOT NULL,
    description TEXT,
    available_capacity INT NOT NULL DEFAULT 1,
    status resource_status NOT NULL DEFAULT 'AVAILABLE',
    requires_approval BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX resources_org_id_idx ON resources (org_id);
CREATE INDEX resources_status_idx ON resources (status);

-- Bookings
CREATE TABLE bookings (
    id UUID
        DEFAULT gen_random_uuid()
        CONSTRAINT bookings_pk PRIMARY KEY,

    resource_id UUID NOT NULL
        CONSTRAINT bookings_resource_id_fkey REFERENCES resources (id),

    reserved_user_id BIGINT NOT NULL
        CONSTRAINT bookings_reserved_user_id_fkey REFERENCES users (id),

    reserved_team_id BIGINT NOT NULL
        CONSTRAINT bookings_reserved_team_id_fkey REFERENCES teams (id),

    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    status booking_status NOT NULL DEFAULT 'PENDING',
    purpose TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT bookings_time_range_check CHECK (end_time > start_time)
);

CREATE INDEX bookings_resource_id_idx ON bookings (resource_id);
CREATE INDEX bookings_reserved_user_id_idx ON bookings (reserved_user_id);
CREATE INDEX bookings_reserved_team_id_idx ON bookings (reserved_team_id);
CREATE INDEX bookings_time_range_idx ON bookings (resource_id, start_time, end_time);

-- Documents
CREATE TABLE documents (
    id UUID
        DEFAULT gen_random_uuid()
        CONSTRAINT documents_pk PRIMARY KEY,

    author_id BIGINT NOT NULL
        CONSTRAINT documents_author_id_fkey REFERENCES users (id),

    team_id BIGINT NOT NULL
        CONSTRAINT documents_team_id_fkey REFERENCES teams (id),

    title VARCHAR(255) NOT NULL,
    is_encrypted BOOLEAN NOT NULL DEFAULT false,
    version INT NOT NULL DEFAULT 1,

    last_edited_by BIGINT NOT NULL
        CONSTRAINT documents_last_edited_by_fkey REFERENCES users (id),

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX documents_team_id_idx ON documents (team_id);
CREATE INDEX documents_author_id_idx ON documents (author_id);

-- Document history
CREATE TABLE document_history (
    id UUID
        DEFAULT gen_random_uuid()
        CONSTRAINT document_history_pk PRIMARY KEY,

    document_id UUID NOT NULL
        CONSTRAINT document_history_document_id_fkey REFERENCES documents (id),

    version INT NOT NULL,

    edited_by BIGINT
        CONSTRAINT document_history_edited_by_fkey REFERENCES users (id),

    edited_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX document_history_document_id_idx ON document_history (document_id);

-- Audit logs
CREATE TABLE audit_logs (
    id UUID
        DEFAULT gen_random_uuid()
        CONSTRAINT audit_logs_pk PRIMARY KEY,

    org_id BIGINT NOT NULL
        CONSTRAINT audit_logs_org_id_fkey REFERENCES orgs (id),

    user_id BIGINT NOT NULL
        CONSTRAINT audit_logs_user_id_fkey REFERENCES users (id),

    team_id BIGINT
        CONSTRAINT audit_logs_team_id_fkey REFERENCES teams (id),

    action VARCHAR(255) NOT NULL,
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX audit_logs_org_id_idx ON audit_logs (org_id);
CREATE INDEX audit_logs_user_id_idx ON audit_logs (user_id);
CREATE INDEX audit_logs_team_id_idx ON audit_logs (team_id);
CREATE INDEX audit_logs_created_at_idx ON audit_logs (created_at);
