// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package tenantdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO chat_messages (team_id, sender_user_public_id, reply_to_public_id, mentions, message)
SELECT NULLIF(current_setting('app.team_id', true), '')::BIGINT,
       synodus_app_user_public_id(),
       $1,
       $2::uuid[],
       $3
WHERE $1::uuid IS NULL
   OR EXISTS (
       SELECT 1
       FROM chat_messages AS reply
       WHERE reply.team_id = NULLIF(current_setting('app.team_id', true), '')::BIGINT
         AND reply.public_id = $1
   )
RETURNING public_id, team_id, sender_user_public_id, reply_to_public_id,
          mentions, message, created_at, deleted_at
`

type CreateChatMessageParams struct {
	ReplyToPublicID pgtype.UUID `json:"reply_to_public_id"`
	Mentions        []uuid.UUID `json:"mentions"`
	Message         string      `json:"message"`
}

type CreateChatMessageRow struct {
	PublicID           uuid.UUID          `json:"public_id"`
	TeamID             int64              `json:"team_id"`
	SenderUserPublicID uuid.UUID          `json:"sender_user_public_id"`
	ReplyToPublicID    pgtype.UUID        `json:"reply_to_public_id"`
	Mentions           []uuid.UUID        `json:"mentions"`
	Message            string             `json:"message"`
	CreatedAt          time.Time          `json:"created_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (CreateChatMessageRow, error) {
	row := q.db.QueryRow(ctx, createChatMessage, arg.ReplyToPublicID, arg.Mentions, arg.Message)
	var i CreateChatMessageRow
	err := row.Scan(
		&i.PublicID,
		&i.TeamID,
		&i.SenderUserPublicID,
		&i.ReplyToPublicID,
		&i.Mentions,
		&i.Message,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listChatMessages = `-- name: ListChatMessages :many
SELECT public_id, team_id, sender_user_public_id, reply_to_public_id,
       mentions, message, created_at, deleted_at
FROM chat_messages
WHERE team_id = NULLIF(current_setting('app.team_id', true), '')::BIGINT
  AND (NOT $1::boolean OR created_at < $2::timestamptz)
ORDER BY created_at DESC, public_id DESC
LIMIT $3
`

type ListChatMessagesParams struct {
	BeforeSet       bool      `json:"before_set"`
	BeforeCreatedAt time.Time `json:"before_created_at"`
	Limit           int32     `json:"limit"`
}

type ListChatMessagesRow struct {
	PublicID           uuid.UUID          `json:"public_id"`
	TeamID             int64              `json:"team_id"`
	SenderUserPublicID uuid.UUID          `json:"sender_user_public_id"`
	ReplyToPublicID    pgtype.UUID        `json:"reply_to_public_id"`
	Mentions           []uuid.UUID        `json:"mentions"`
	Message            string             `json:"message"`
	CreatedAt          time.Time          `json:"created_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListChatMessages(ctx context.Context, arg ListChatMessagesParams) ([]ListChatMessagesRow, error) {
	rows, err := q.db.Query(ctx, listChatMessages, arg.BeforeSet, arg.BeforeCreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatMessagesRow
	for rows.Next() {
		var i ListChatMessagesRow
		if err := rows.Scan(
			&i.PublicID,
			&i.TeamID,
			&i.SenderUserPublicID,
			&i.ReplyToPublicID,
			&i.Mentions,
			&i.Message,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteChatMessage = `-- name: SoftDeleteChatMessage :one
UPDATE chat_messages AS message
SET deleted_at = now()
WHERE message.team_id = NULLIF(current_setting('app.team_id', true), '')::BIGINT
  AND message.public_id = $1
  AND message.deleted_at IS NULL
RETURNING message.public_id, message.team_id, message.sender_user_public_id,
          message.reply_to_public_id, message.mentions, message.message,
          message.created_at, message.deleted_at
`

type SoftDeleteChatMessageRow struct {
	PublicID           uuid.UUID          `json:"public_id"`
	TeamID             int64              `json:"team_id"`
	SenderUserPublicID uuid.UUID          `json:"sender_user_public_id"`
	ReplyToPublicID    pgtype.UUID        `json:"reply_to_public_id"`
	Mentions           []uuid.UUID        `json:"mentions"`
	Message            string             `json:"message"`
	CreatedAt          time.Time          `json:"created_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) SoftDeleteChatMessage(ctx context.Context, publicID uuid.UUID) (SoftDeleteChatMessageRow, error) {
	row := q.db.QueryRow(ctx, softDeleteChatMessage, publicID)
	var i SoftDeleteChatMessageRow
	err := row.Scan(
		&i.PublicID,
		&i.TeamID,
		&i.SenderUserPublicID,
		&i.ReplyToPublicID,
		&i.Mentions,
		&i.Message,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
