// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content_access.sql

package tenantdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const decideContentAccess = `-- name: DecideContentAccess :one
UPDATE content_access_requests r
SET status = $1, updated_at = now()
FROM content_owners o
WHERE r.public_id = $2 AND r.status = 'pending'
  AND o.kind = r.kind AND o.resource_id = r.resource_id
  AND o.creator_id = synodus_app_user_public_id()
  AND ($1::text = 'denied' OR EXISTS (
      SELECT 1 FROM team_members m WHERE m.team_id = o.team_id AND m.user_public_id = r.requested_by))
RETURNING r.public_id, r.kind, r.resource_id, r.requested_by, r.status, r.updated_at
`

type DecideContentAccessParams struct {
	Status   string    `json:"status"`
	PublicID uuid.UUID `json:"public_id"`
}

func (q *Queries) DecideContentAccess(ctx context.Context, arg DecideContentAccessParams) (ContentAccessRequest, error) {
	row := q.db.QueryRow(ctx, decideContentAccess, arg.Status, arg.PublicID)
	var i ContentAccessRequest
	err := row.Scan(
		&i.PublicID,
		&i.Kind,
		&i.ResourceID,
		&i.RequestedBy,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const grantContentAccess = `-- name: GrantContentAccess :one
INSERT INTO content_access_requests (kind, resource_id, requested_by, status)
SELECT o.kind, o.resource_id, $1::uuid, 'granted'
FROM content_owners o
WHERE o.kind = $2 AND o.resource_id = $3
  AND o.creator_id = synodus_app_user_public_id()
  AND EXISTS (SELECT 1 FROM team_members m WHERE m.team_id = o.team_id AND m.user_public_id = $1::uuid)
ON CONFLICT (kind, resource_id, requested_by) DO UPDATE
SET status = 'granted', updated_at = now()
RETURNING public_id, kind, resource_id, requested_by, status, updated_at
`

type GrantContentAccessParams struct {
	RequestedBy uuid.UUID `json:"requested_by"`
	Kind        string    `json:"kind"`
	ResourceID  uuid.UUID `json:"resource_id"`
}

func (q *Queries) GrantContentAccess(ctx context.Context, arg GrantContentAccessParams) (ContentAccessRequest, error) {
	row := q.db.QueryRow(ctx, grantContentAccess, arg.RequestedBy, arg.Kind, arg.ResourceID)
	var i ContentAccessRequest
	err := row.Scan(
		&i.PublicID,
		&i.Kind,
		&i.ResourceID,
		&i.RequestedBy,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const listContentAccess = `-- name: ListContentAccess :many
SELECT o.kind, o.resource_id, o.creator_id,
       synodus_can_access_content(o.kind, o.resource_id)::boolean AS can_access
FROM content_owners o
ORDER BY o.kind, o.resource_id
LIMIT $1
`

type ListContentAccessRow struct {
	Kind       string    `json:"kind"`
	ResourceID uuid.UUID `json:"resource_id"`
	CreatorID  uuid.UUID `json:"creator_id"`
	CanAccess  bool      `json:"can_access"`
}

func (q *Queries) ListContentAccess(ctx context.Context, limit int32) ([]ListContentAccessRow, error) {
	rows, err := q.db.Query(ctx, listContentAccess, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContentAccessRow
	for rows.Next() {
		var i ListContentAccessRow
		if err := rows.Scan(
			&i.Kind,
			&i.ResourceID,
			&i.CreatorID,
			&i.CanAccess,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentAccessRequests = `-- name: ListContentAccessRequests :many
SELECT r.public_id, r.kind, r.resource_id, r.requested_by, r.status, r.updated_at,
       coalesce(synodus_user_display_name(r.requested_by), '')::text AS requester_name
FROM content_access_requests r
ORDER BY r.updated_at DESC, r.public_id
LIMIT $1
`

type ListContentAccessRequestsRow struct {
	PublicID      uuid.UUID `json:"public_id"`
	Kind          string    `json:"kind"`
	ResourceID    uuid.UUID `json:"resource_id"`
	RequestedBy   uuid.UUID `json:"requested_by"`
	Status        string    `json:"status"`
	UpdatedAt     time.Time `json:"updated_at"`
	RequesterName string    `json:"requester_name"`
}

func (q *Queries) ListContentAccessRequests(ctx context.Context, limit int32) ([]ListContentAccessRequestsRow, error) {
	rows, err := q.db.Query(ctx, listContentAccessRequests, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContentAccessRequestsRow
	for rows.Next() {
		var i ListContentAccessRequestsRow
		if err := rows.Scan(
			&i.PublicID,
			&i.Kind,
			&i.ResourceID,
			&i.RequestedBy,
			&i.Status,
			&i.UpdatedAt,
			&i.RequesterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestContentAccess = `-- name: RequestContentAccess :one
INSERT INTO content_access_requests (kind, resource_id, requested_by)
SELECT o.kind, o.resource_id, synodus_app_user_public_id()
FROM content_owners o
WHERE o.kind = $1 AND o.resource_id = $2
  AND o.creator_id <> synodus_app_user_public_id()
ON CONFLICT (kind, resource_id, requested_by) DO UPDATE
SET status = 'pending', updated_at = now()
WHERE content_access_requests.status = 'denied'
RETURNING public_id, kind, resource_id, requested_by, status, updated_at
`

type RequestContentAccessParams struct {
	Kind       string    `json:"kind"`
	ResourceID uuid.UUID `json:"resource_id"`
}

func (q *Queries) RequestContentAccess(ctx context.Context, arg RequestContentAccessParams) (ContentAccessRequest, error) {
	row := q.db.QueryRow(ctx, requestContentAccess, arg.Kind, arg.ResourceID)
	var i ContentAccessRequest
	err := row.Scan(
		&i.PublicID,
		&i.Kind,
		&i.ResourceID,
		&i.RequestedBy,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}
