// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package tenantdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (team_id, title, last_updated_by)
VALUES ($1, $2, $3)
RETURNING id, public_id, team_id, canonical_state, title, body_html, last_updated_by, created_at, updated_at
`

type CreateDocumentParams struct {
	TeamID        int64     `json:"team_id"`
	Title         string    `json:"title"`
	LastUpdatedBy uuid.UUID `json:"last_updated_by"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument, arg.TeamID, arg.Title, arg.LastUpdatedBy)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TeamID,
		&i.CanonicalState,
		&i.Title,
		&i.BodyHtml,
		&i.LastUpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :execrows
DELETE FROM documents
WHERE public_id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, publicID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDocument, publicID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDocumentForTeam = `-- name: GetDocumentForTeam :one
SELECT id, public_id, team_id, canonical_state, title, body_html, last_updated_by, created_at, updated_at
FROM documents
WHERE team_id = $1 AND public_id = $2
`

type GetDocumentForTeamParams struct {
	TeamID   int64     `json:"team_id"`
	PublicID uuid.UUID `json:"public_id"`
}

func (q *Queries) GetDocumentForTeam(ctx context.Context, arg GetDocumentForTeamParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentForTeam, arg.TeamID, arg.PublicID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TeamID,
		&i.CanonicalState,
		&i.Title,
		&i.BodyHtml,
		&i.LastUpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocumentsForTeam = `-- name: ListDocumentsForTeam :many
SELECT id, public_id, team_id, title, body_html, last_updated_by, created_at, updated_at
FROM documents
WHERE team_id = $1
ORDER BY updated_at DESC, public_id DESC
LIMIT $2
`

type ListDocumentsForTeamParams struct {
	TeamID int64 `json:"team_id"`
	Limit  int32 `json:"limit"`
}

type ListDocumentsForTeamRow struct {
	ID            int64     `json:"id"`
	PublicID      uuid.UUID `json:"public_id"`
	TeamID        int64     `json:"team_id"`
	Title         string    `json:"title"`
	BodyHtml      string    `json:"body_html"`
	LastUpdatedBy uuid.UUID `json:"last_updated_by"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) ListDocumentsForTeam(ctx context.Context, arg ListDocumentsForTeamParams) ([]ListDocumentsForTeamRow, error) {
	rows, err := q.db.Query(ctx, listDocumentsForTeam, arg.TeamID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsForTeamRow
	for rows.Next() {
		var i ListDocumentsForTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TeamID,
			&i.Title,
			&i.BodyHtml,
			&i.LastUpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents
SET title = COALESCE($1, title),
    body_html = COALESCE($2, body_html),
    last_updated_by = $3,
    updated_at = NOW()
WHERE public_id = $4
RETURNING id, public_id, team_id, canonical_state, title, body_html, last_updated_by, created_at, updated_at
`

type UpdateDocumentParams struct {
	Title         pgtype.Text `json:"title"`
	BodyHtml      pgtype.Text `json:"body_html"`
	LastUpdatedBy uuid.UUID   `json:"last_updated_by"`
	PublicID      uuid.UUID   `json:"public_id"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocument,
		arg.Title,
		arg.BodyHtml,
		arg.LastUpdatedBy,
		arg.PublicID,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TeamID,
		&i.CanonicalState,
		&i.Title,
		&i.BodyHtml,
		&i.LastUpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
