// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: key_access_requests.sql

package tenantdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createKeyAccessRequest = `-- name: CreateKeyAccessRequest :one
INSERT INTO team_key_access_requests (team_id, requested_by)
SELECT team.id, synodus_app_user_public_id()
FROM teams AS team
WHERE team.id = NULLIF(current_setting('app.team_id', true), '')::BIGINT
RETURNING id, public_id, team_id, requested_by, status, created_at, decided_by, decided_at,
          (SELECT public_id FROM teams WHERE id = team_id) AS team_public_id,
          (SELECT name FROM teams WHERE id = team_id) AS team_name,
          synodus_user_display_name(requested_by) AS requested_by_name
`

type CreateKeyAccessRequestRow struct {
	ID              int64              `json:"id"`
	PublicID        uuid.UUID          `json:"public_id"`
	TeamID          int64              `json:"team_id"`
	RequestedBy     uuid.UUID          `json:"requested_by"`
	Status          string             `json:"status"`
	CreatedAt       time.Time          `json:"created_at"`
	DecidedBy       pgtype.UUID        `json:"decided_by"`
	DecidedAt       pgtype.Timestamptz `json:"decided_at"`
	TeamPublicID    uuid.UUID          `json:"team_public_id"`
	TeamName        string             `json:"team_name"`
	RequestedByName string             `json:"requested_by_name"`
}

func (q *Queries) CreateKeyAccessRequest(ctx context.Context) (CreateKeyAccessRequestRow, error) {
	row := q.db.QueryRow(ctx, createKeyAccessRequest)
	var i CreateKeyAccessRequestRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TeamID,
		&i.RequestedBy,
		&i.Status,
		&i.CreatedAt,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.TeamPublicID,
		&i.TeamName,
		&i.RequestedByName,
	)
	return i, err
}

const decideKeyAccessRequest = `-- name: DecideKeyAccessRequest :one
UPDATE team_key_access_requests
SET status = $1, decided_by = synodus_app_user_public_id(), decided_at = now()
WHERE team_key_access_requests.public_id = $2 AND status = 'pending'
RETURNING id, public_id, team_id, requested_by, status, created_at, decided_by, decided_at,
          (SELECT public_id FROM teams WHERE id = team_id) AS team_public_id,
          (SELECT name FROM teams WHERE id = team_id) AS team_name,
          synodus_user_display_name(requested_by) AS requested_by_name,
          synodus_user_display_name(decided_by) AS decided_by_name
`

type DecideKeyAccessRequestParams struct {
	Status   string    `json:"status"`
	PublicID uuid.UUID `json:"public_id"`
}

type DecideKeyAccessRequestRow struct {
	ID              int64              `json:"id"`
	PublicID        uuid.UUID          `json:"public_id"`
	TeamID          int64              `json:"team_id"`
	RequestedBy     uuid.UUID          `json:"requested_by"`
	Status          string             `json:"status"`
	CreatedAt       time.Time          `json:"created_at"`
	DecidedBy       pgtype.UUID        `json:"decided_by"`
	DecidedAt       pgtype.Timestamptz `json:"decided_at"`
	TeamPublicID    uuid.UUID          `json:"team_public_id"`
	TeamName        string             `json:"team_name"`
	RequestedByName string             `json:"requested_by_name"`
	DecidedByName   string             `json:"decided_by_name"`
}

func (q *Queries) DecideKeyAccessRequest(ctx context.Context, arg DecideKeyAccessRequestParams) (DecideKeyAccessRequestRow, error) {
	row := q.db.QueryRow(ctx, decideKeyAccessRequest, arg.Status, arg.PublicID)
	var i DecideKeyAccessRequestRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TeamID,
		&i.RequestedBy,
		&i.Status,
		&i.CreatedAt,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.TeamPublicID,
		&i.TeamName,
		&i.RequestedByName,
		&i.DecidedByName,
	)
	return i, err
}

const getKeyAccessRequest = `-- name: GetKeyAccessRequest :one
SELECT id, public_id, team_id, requested_by, status, created_at, decided_by, decided_at,
       (SELECT public_id FROM teams WHERE id = team_id) AS team_public_id,
       (SELECT name FROM teams WHERE id = team_id) AS team_name,
       synodus_user_display_name(requested_by) AS requested_by_name
FROM team_key_access_requests
WHERE team_key_access_requests.public_id = $1
`

type GetKeyAccessRequestRow struct {
	ID              int64              `json:"id"`
	PublicID        uuid.UUID          `json:"public_id"`
	TeamID          int64              `json:"team_id"`
	RequestedBy     uuid.UUID          `json:"requested_by"`
	Status          string             `json:"status"`
	CreatedAt       time.Time          `json:"created_at"`
	DecidedBy       pgtype.UUID        `json:"decided_by"`
	DecidedAt       pgtype.Timestamptz `json:"decided_at"`
	TeamPublicID    uuid.UUID          `json:"team_public_id"`
	TeamName        string             `json:"team_name"`
	RequestedByName string             `json:"requested_by_name"`
}

func (q *Queries) GetKeyAccessRequest(ctx context.Context, publicID uuid.UUID) (GetKeyAccessRequestRow, error) {
	row := q.db.QueryRow(ctx, getKeyAccessRequest, publicID)
	var i GetKeyAccessRequestRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TeamID,
		&i.RequestedBy,
		&i.Status,
		&i.CreatedAt,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.TeamPublicID,
		&i.TeamName,
		&i.RequestedByName,
	)
	return i, err
}

const listKeyAccessRequests = `-- name: ListKeyAccessRequests :many
SELECT request.public_id, request.requested_by,
       synodus_user_display_name(request.requested_by) AS requested_by_name,
       request.status, request.created_at, request.decided_at,
       request.decided_by, coalesce(synodus_user_display_name(request.decided_by), '')::text AS decided_by_name,
       team.public_id AS team_public_id, team.name AS team_name
FROM team_key_access_requests AS request
JOIN teams AS team ON team.id = request.team_id
ORDER BY request.created_at DESC, request.public_id
LIMIT $1
`

type ListKeyAccessRequestsRow struct {
	PublicID        uuid.UUID          `json:"public_id"`
	RequestedBy     uuid.UUID          `json:"requested_by"`
	RequestedByName string             `json:"requested_by_name"`
	Status          string             `json:"status"`
	CreatedAt       time.Time          `json:"created_at"`
	DecidedAt       pgtype.Timestamptz `json:"decided_at"`
	DecidedBy       pgtype.UUID        `json:"decided_by"`
	DecidedByName   string             `json:"decided_by_name"`
	TeamPublicID    uuid.UUID          `json:"team_public_id"`
	TeamName        string             `json:"team_name"`
}

func (q *Queries) ListKeyAccessRequests(ctx context.Context, limit int32) ([]ListKeyAccessRequestsRow, error) {
	rows, err := q.db.Query(ctx, listKeyAccessRequests, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKeyAccessRequestsRow
	for rows.Next() {
		var i ListKeyAccessRequestsRow
		if err := rows.Scan(
			&i.PublicID,
			&i.RequestedBy,
			&i.RequestedByName,
			&i.Status,
			&i.CreatedAt,
			&i.DecidedAt,
			&i.DecidedBy,
			&i.DecidedByName,
			&i.TeamPublicID,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
