// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package tenantdb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ChatMessage struct {
	ID                 int64              `json:"id"`
	PublicID           uuid.UUID          `json:"public_id"`
	TeamID             int64              `json:"team_id"`
	SenderUserPublicID uuid.UUID          `json:"sender_user_public_id"`
	ReplyToPublicID    pgtype.UUID        `json:"reply_to_public_id"`
	Mentions           []uuid.UUID        `json:"mentions"`
	Message            string             `json:"message"`
	CreatedAt          time.Time          `json:"created_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type ContentAccessRequest struct {
	PublicID    uuid.UUID `json:"public_id"`
	Kind        string    `json:"kind"`
	ResourceID  uuid.UUID `json:"resource_id"`
	RequestedBy uuid.UUID `json:"requested_by"`
	Status      string    `json:"status"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ContentOwner struct {
	Kind       string    `json:"kind"`
	ResourceID uuid.UUID `json:"resource_id"`
	TeamID     int64     `json:"team_id"`
	CreatorID  uuid.UUID `json:"creator_id"`
}

type Document struct {
	ID             int64     `json:"id"`
	PublicID       uuid.UUID `json:"public_id"`
	TeamID         int64     `json:"team_id"`
	CanonicalState []byte    `json:"canonical_state"`
	Title          string    `json:"title"`
	BodyHtml       string    `json:"body_html"`
	LastUpdatedBy  uuid.UUID `json:"last_updated_by"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type File struct {
	ID          int64              `json:"id"`
	PublicID    uuid.UUID          `json:"public_id"`
	TeamID      int64              `json:"team_id"`
	Name        string             `json:"name"`
	Size        int64              `json:"size"`
	ContentType string             `json:"content_type"`
	ObjectKey   string             `json:"object_key"`
	Iv          []byte             `json:"iv"`
	KeyVersion  int32              `json:"key_version"`
	UploadedBy  uuid.UUID          `json:"uploaded_by"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Resource struct {
	ID           int64     `json:"id"`
	PublicID     uuid.UUID `json:"public_id"`
	Name         string    `json:"name"`
	Code         string    `json:"code"`
	Kind         string    `json:"kind"`
	Location     string    `json:"location"`
	Enabled      bool      `json:"enabled"`
	Availability []byte    `json:"availability"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type ResourceRequest struct {
	ID          int64              `json:"id"`
	PublicID    uuid.UUID          `json:"public_id"`
	ResourceID  int64              `json:"resource_id"`
	TeamID      int64              `json:"team_id"`
	RequestedBy uuid.UUID          `json:"requested_by"`
	StartTime   time.Time          `json:"start_time"`
	EndTime     time.Time          `json:"end_time"`
	Purpose     string             `json:"purpose"`
	Status      string             `json:"status"`
	CreatedAt   time.Time          `json:"created_at"`
	DecidedAt   pgtype.Timestamptz `json:"decided_at"`
}

type Task struct {
	ID               int64              `json:"id"`
	TeamID           int64              `json:"team_id"`
	Description      string             `json:"description"`
	Status           string             `json:"status"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	PublicID         uuid.UUID          `json:"public_id"`
	AssigneePublicID pgtype.UUID        `json:"assignee_public_id"`
	StartDate        pgtype.Timestamptz `json:"start_date"`
	DueDate          pgtype.Timestamptz `json:"due_date"`
	Details          string             `json:"details"`
}

type Team struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	Slug         string             `json:"slug"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	PublicID     uuid.UUID          `json:"public_id"`
	IsQuarantine bool               `json:"is_quarantine"`
	Description  string             `json:"description"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type TeamAiSetting struct {
	TeamID      int64  `json:"team_id"`
	EndpointUrl string `json:"endpoint_url"`
	Model       string `json:"model"`
	ApiToken    string `json:"api_token"`
}

type TeamKey struct {
	ID        int64     `json:"id"`
	TeamID    int64     `json:"team_id"`
	Version   int32     `json:"version"`
	Status    string    `json:"status"`
	Algorithm string    `json:"algorithm"`
	Wraps     []byte    `json:"wraps"`
	CreatedBy uuid.UUID `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
}

type TeamKeyAccessRequest struct {
	ID          int64              `json:"id"`
	PublicID    uuid.UUID          `json:"public_id"`
	TeamID      int64              `json:"team_id"`
	RequestedBy uuid.UUID          `json:"requested_by"`
	Status      string             `json:"status"`
	CreatedAt   time.Time          `json:"created_at"`
	DecidedBy   pgtype.UUID        `json:"decided_by"`
	DecidedAt   pgtype.Timestamptz `json:"decided_at"`
}

type TeamMember struct {
	TeamID       int64     `json:"team_id"`
	UserPublicID uuid.UUID `json:"user_public_id"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
