// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources.sql

package tenantdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approvedResourceRequestOverlap = `-- name: ApprovedResourceRequestOverlap :one
SELECT EXISTS (
    SELECT 1 FROM resource_requests
    WHERE resource_id = $1 AND status = 'approved'
      AND start_time < $2 AND $3 < end_time
      AND public_id <> $4
) AS overlaps
`

type ApprovedResourceRequestOverlapParams struct {
	ResourceID      int64     `json:"resource_id"`
	EndTime         time.Time `json:"end_time"`
	StartTime       time.Time `json:"start_time"`
	RequestPublicID uuid.UUID `json:"request_public_id"`
}

func (q *Queries) ApprovedResourceRequestOverlap(ctx context.Context, arg ApprovedResourceRequestOverlapParams) (bool, error) {
	row := q.db.QueryRow(ctx, approvedResourceRequestOverlap,
		arg.ResourceID,
		arg.EndTime,
		arg.StartTime,
		arg.RequestPublicID,
	)
	var overlaps bool
	err := row.Scan(&overlaps)
	return overlaps, err
}

const createResource = `-- name: CreateResource :one
INSERT INTO resources (name, code, kind, location, enabled, availability)
VALUES ($1, $2, $3, $4,
        $5, $6)
RETURNING id, public_id, name, code, kind, location, enabled, availability, created_at, updated_at
`

type CreateResourceParams struct {
	Name         string `json:"name"`
	Code         string `json:"code"`
	Kind         string `json:"kind"`
	Location     string `json:"location"`
	Enabled      bool   `json:"enabled"`
	Availability []byte `json:"availability"`
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, createResource,
		arg.Name,
		arg.Code,
		arg.Kind,
		arg.Location,
		arg.Enabled,
		arg.Availability,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Code,
		&i.Kind,
		&i.Location,
		&i.Enabled,
		&i.Availability,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createResourceRequest = `-- name: CreateResourceRequest :one
INSERT INTO resource_requests (resource_id, team_id, requested_by, start_time, end_time, purpose)
SELECT resource.id, team.id, synodus_app_user_public_id(), $1,
       $2, $3
FROM resources AS resource
JOIN teams AS team ON team.id = nullif(current_setting('app.team_id', true), '')::bigint
WHERE resource.public_id = $4 AND team.public_id = $5
RETURNING id, public_id, resource_id, team_id, requested_by, start_time, end_time,
          purpose, status, created_at, decided_at
`

type CreateResourceRequestParams struct {
	StartTime        time.Time `json:"start_time"`
	EndTime          time.Time `json:"end_time"`
	Purpose          string    `json:"purpose"`
	ResourcePublicID uuid.UUID `json:"resource_public_id"`
	TeamPublicID     uuid.UUID `json:"team_public_id"`
}

func (q *Queries) CreateResourceRequest(ctx context.Context, arg CreateResourceRequestParams) (ResourceRequest, error) {
	row := q.db.QueryRow(ctx, createResourceRequest,
		arg.StartTime,
		arg.EndTime,
		arg.Purpose,
		arg.ResourcePublicID,
		arg.TeamPublicID,
	)
	var i ResourceRequest
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.ResourceID,
		&i.TeamID,
		&i.RequestedBy,
		&i.StartTime,
		&i.EndTime,
		&i.Purpose,
		&i.Status,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const decideResourceRequest = `-- name: DecideResourceRequest :one
UPDATE resource_requests
SET status = $1, decided_at = now()
WHERE public_id = $2 AND status = 'pending'
RETURNING id, public_id, resource_id, team_id, requested_by, start_time, end_time,
          purpose, status, created_at, decided_at
`

type DecideResourceRequestParams struct {
	Status   string    `json:"status"`
	PublicID uuid.UUID `json:"public_id"`
}

func (q *Queries) DecideResourceRequest(ctx context.Context, arg DecideResourceRequestParams) (ResourceRequest, error) {
	row := q.db.QueryRow(ctx, decideResourceRequest, arg.Status, arg.PublicID)
	var i ResourceRequest
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.ResourceID,
		&i.TeamID,
		&i.RequestedBy,
		&i.StartTime,
		&i.EndTime,
		&i.Purpose,
		&i.Status,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const deleteResource = `-- name: DeleteResource :execrows
DELETE FROM resources WHERE public_id = $1
`

func (q *Queries) DeleteResource(ctx context.Context, publicID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteResource, publicID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getResource = `-- name: GetResource :one
SELECT id, public_id, name, code, kind, location, enabled, availability, created_at, updated_at
FROM resources WHERE public_id = $1
`

func (q *Queries) GetResource(ctx context.Context, publicID uuid.UUID) (Resource, error) {
	row := q.db.QueryRow(ctx, getResource, publicID)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Code,
		&i.Kind,
		&i.Location,
		&i.Enabled,
		&i.Availability,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResourceRequest = `-- name: GetResourceRequest :one
SELECT request.id, request.public_id, request.resource_id, request.team_id, request.requested_by,
       request.start_time, request.end_time, request.purpose, request.status, request.created_at,
       request.decided_at, resource.public_id AS resource_public_id, resource.name AS resource_name,
       resource.enabled, resource.availability, team.public_id AS team_public_id, team.name AS team_name,
       synodus_user_display_name(request.requested_by) AS requested_by_name
FROM resource_requests AS request
JOIN resources AS resource ON resource.id = request.resource_id
JOIN teams AS team ON team.id = request.team_id
WHERE request.public_id = $1
`

type GetResourceRequestRow struct {
	ID               int64              `json:"id"`
	PublicID         uuid.UUID          `json:"public_id"`
	ResourceID       int64              `json:"resource_id"`
	TeamID           int64              `json:"team_id"`
	RequestedBy      uuid.UUID          `json:"requested_by"`
	StartTime        time.Time          `json:"start_time"`
	EndTime          time.Time          `json:"end_time"`
	Purpose          string             `json:"purpose"`
	Status           string             `json:"status"`
	CreatedAt        time.Time          `json:"created_at"`
	DecidedAt        pgtype.Timestamptz `json:"decided_at"`
	ResourcePublicID uuid.UUID          `json:"resource_public_id"`
	ResourceName     string             `json:"resource_name"`
	Enabled          bool               `json:"enabled"`
	Availability     []byte             `json:"availability"`
	TeamPublicID     uuid.UUID          `json:"team_public_id"`
	TeamName         string             `json:"team_name"`
	RequestedByName  string             `json:"requested_by_name"`
}

func (q *Queries) GetResourceRequest(ctx context.Context, publicID uuid.UUID) (GetResourceRequestRow, error) {
	row := q.db.QueryRow(ctx, getResourceRequest, publicID)
	var i GetResourceRequestRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.ResourceID,
		&i.TeamID,
		&i.RequestedBy,
		&i.StartTime,
		&i.EndTime,
		&i.Purpose,
		&i.Status,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.ResourcePublicID,
		&i.ResourceName,
		&i.Enabled,
		&i.Availability,
		&i.TeamPublicID,
		&i.TeamName,
		&i.RequestedByName,
	)
	return i, err
}

const listBookings = `-- name: ListBookings :many
SELECT request.public_id, resource.public_id AS resource_public_id, resource.name AS resource_name,
       request.start_time, request.end_time,
       coalesce(synodus_current_organization_role() IN ('owner', 'administrator') OR team_member.user_public_id IS NOT NULL, false)::boolean AS details_visible,
       coalesce(CASE WHEN synodus_current_organization_role() IN ('owner', 'administrator') OR team_member.user_public_id IS NOT NULL THEN team.public_id END, '00000000-0000-0000-0000-000000000000'::uuid)::uuid AS team_public_id,
       coalesce(CASE WHEN synodus_current_organization_role() IN ('owner', 'administrator') OR team_member.user_public_id IS NOT NULL THEN team.name END, '')::text AS team_name,
       coalesce(CASE WHEN synodus_current_organization_role() IN ('owner', 'administrator') OR team_member.user_public_id IS NOT NULL THEN synodus_user_display_name(request.requested_by) END, '')::text AS requested_by_name,
       coalesce(CASE WHEN synodus_current_organization_role() IN ('owner', 'administrator') OR team_member.user_public_id IS NOT NULL THEN request.purpose END, '')::text AS purpose
FROM resource_requests AS request
JOIN resources AS resource ON resource.id = request.resource_id
JOIN teams AS team ON team.id = request.team_id
LEFT JOIN team_members AS team_member ON team_member.team_id = request.team_id
    AND team_member.user_public_id = synodus_app_user_public_id()
WHERE request.status = 'approved'
ORDER BY request.start_time, request.public_id
LIMIT $1
`

type ListBookingsRow struct {
	PublicID         uuid.UUID `json:"public_id"`
	ResourcePublicID uuid.UUID `json:"resource_public_id"`
	ResourceName     string    `json:"resource_name"`
	StartTime        time.Time `json:"start_time"`
	EndTime          time.Time `json:"end_time"`
	DetailsVisible   bool      `json:"details_visible"`
	TeamPublicID     uuid.UUID `json:"team_public_id"`
	TeamName         string    `json:"team_name"`
	RequestedByName  string    `json:"requested_by_name"`
	Purpose          string    `json:"purpose"`
}

func (q *Queries) ListBookings(ctx context.Context, limit int32) ([]ListBookingsRow, error) {
	rows, err := q.db.Query(ctx, listBookings, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookingsRow
	for rows.Next() {
		var i ListBookingsRow
		if err := rows.Scan(
			&i.PublicID,
			&i.ResourcePublicID,
			&i.ResourceName,
			&i.StartTime,
			&i.EndTime,
			&i.DetailsVisible,
			&i.TeamPublicID,
			&i.TeamName,
			&i.RequestedByName,
			&i.Purpose,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceRequests = `-- name: ListResourceRequests :many
SELECT request.public_id, resource.public_id AS resource_public_id, resource.name AS resource_name,
       team.public_id AS team_public_id, team.name AS team_name, request.requested_by,
       synodus_user_display_name(request.requested_by) AS requested_by_name, request.start_time, request.end_time,
       request.purpose, request.status, request.created_at, request.decided_at
FROM resource_requests AS request
JOIN resources AS resource ON resource.id = request.resource_id
JOIN teams AS team ON team.id = request.team_id
LEFT JOIN team_members AS team_member ON team_member.team_id = request.team_id
    AND team_member.user_public_id = synodus_app_user_public_id()
WHERE synodus_current_organization_role() IN ('owner', 'administrator') OR team_member.user_public_id IS NOT NULL
ORDER BY request.created_at DESC, request.public_id
LIMIT $1
`

type ListResourceRequestsRow struct {
	PublicID         uuid.UUID          `json:"public_id"`
	ResourcePublicID uuid.UUID          `json:"resource_public_id"`
	ResourceName     string             `json:"resource_name"`
	TeamPublicID     uuid.UUID          `json:"team_public_id"`
	TeamName         string             `json:"team_name"`
	RequestedBy      uuid.UUID          `json:"requested_by"`
	RequestedByName  string             `json:"requested_by_name"`
	StartTime        time.Time          `json:"start_time"`
	EndTime          time.Time          `json:"end_time"`
	Purpose          string             `json:"purpose"`
	Status           string             `json:"status"`
	CreatedAt        time.Time          `json:"created_at"`
	DecidedAt        pgtype.Timestamptz `json:"decided_at"`
}

func (q *Queries) ListResourceRequests(ctx context.Context, limit int32) ([]ListResourceRequestsRow, error) {
	rows, err := q.db.Query(ctx, listResourceRequests, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListResourceRequestsRow
	for rows.Next() {
		var i ListResourceRequestsRow
		if err := rows.Scan(
			&i.PublicID,
			&i.ResourcePublicID,
			&i.ResourceName,
			&i.TeamPublicID,
			&i.TeamName,
			&i.RequestedBy,
			&i.RequestedByName,
			&i.StartTime,
			&i.EndTime,
			&i.Purpose,
			&i.Status,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResources = `-- name: ListResources :many
SELECT id, public_id, name, code, kind, location, enabled, availability, created_at, updated_at
FROM resources ORDER BY name, public_id
LIMIT $1
`

func (q *Queries) ListResources(ctx context.Context, limit int32) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResources, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Name,
			&i.Code,
			&i.Kind,
			&i.Location,
			&i.Enabled,
			&i.Availability,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockResourceForDecision = `-- name: LockResourceForDecision :one
SELECT resource.id, resource.enabled, resource.availability
FROM resources AS resource
JOIN resource_requests AS request ON request.resource_id = resource.id
WHERE request.public_id = $1
FOR UPDATE OF resource
`

type LockResourceForDecisionRow struct {
	ID           int64  `json:"id"`
	Enabled      bool   `json:"enabled"`
	Availability []byte `json:"availability"`
}

func (q *Queries) LockResourceForDecision(ctx context.Context, requestPublicID uuid.UUID) (LockResourceForDecisionRow, error) {
	row := q.db.QueryRow(ctx, lockResourceForDecision, requestPublicID)
	var i LockResourceForDecisionRow
	err := row.Scan(&i.ID, &i.Enabled, &i.Availability)
	return i, err
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources SET name = $1, code = $2, kind = $3,
    location = $4, enabled = $5,
    availability = $6, updated_at = now()
WHERE public_id = $7
RETURNING id, public_id, name, code, kind, location, enabled, availability, created_at, updated_at
`

type UpdateResourceParams struct {
	Name         string    `json:"name"`
	Code         string    `json:"code"`
	Kind         string    `json:"kind"`
	Location     string    `json:"location"`
	Enabled      bool      `json:"enabled"`
	Availability []byte    `json:"availability"`
	PublicID     uuid.UUID `json:"public_id"`
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, updateResource,
		arg.Name,
		arg.Code,
		arg.Kind,
		arg.Location,
		arg.Enabled,
		arg.Availability,
		arg.PublicID,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Code,
		&i.Kind,
		&i.Location,
		&i.Enabled,
		&i.Availability,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
