// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package tenantdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (team_id, description, status)
VALUES (NULLIF(current_setting('app.team_id', true), '')::BIGINT, $1, $2)
RETURNING id, team_id, description, status, created_at, updated_at, public_id
`

type CreateTaskParams struct {
	Description string `json:"description"`
	Status      string `json:"status"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask, arg.Description, arg.Status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicID,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :one
DELETE FROM tasks
WHERE public_id = $1
RETURNING id, team_id, description, status, created_at, updated_at, public_id
`

func (q *Queries) DeleteTask(ctx context.Context, publicID uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, deleteTask, publicID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicID,
	)
	return i, err
}

const getTasks = `-- name: GetTasks :many
SELECT tasks.id, tasks.team_id, tasks.description, tasks.status, tasks.created_at, tasks.updated_at, tasks.public_id
FROM tasks
ORDER BY tasks.created_at ASC, tasks.id ASC
LIMIT $1
`

func (q *Queries) GetTasks(ctx context.Context, limit int32) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksAfter = `-- name: GetTasksAfter :many
SELECT tasks.id, tasks.team_id, tasks.description, tasks.status, tasks.created_at, tasks.updated_at, tasks.public_id
FROM tasks
WHERE (tasks.created_at, tasks.public_id) > ($1, $2::uuid)
ORDER BY tasks.created_at ASC, tasks.public_id ASC
LIMIT $3
`

type GetTasksAfterParams struct {
	AfterCreatedAt time.Time `json:"after_created_at"`
	AfterPublicID  uuid.UUID `json:"after_public_id"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) GetTasksAfter(ctx context.Context, arg GetTasksAfterParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasksAfter, arg.AfterCreatedAt, arg.AfterPublicID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksBefore = `-- name: GetTasksBefore :many
SELECT tasks.id, tasks.team_id, tasks.description, tasks.status, tasks.created_at, tasks.updated_at, tasks.public_id
FROM tasks
WHERE (tasks.created_at, tasks.public_id) < ($1, $2::uuid)
ORDER BY tasks.created_at DESC, tasks.public_id DESC
LIMIT $3
`

type GetTasksBeforeParams struct {
	BeforeCreatedAt time.Time `json:"before_created_at"`
	BeforePublicID  uuid.UUID `json:"before_public_id"`
	Limit           int32     `json:"limit"`
}

func (q *Queries) GetTasksBefore(ctx context.Context, arg GetTasksBeforeParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasksBefore, arg.BeforeCreatedAt, arg.BeforePublicID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isolationProbeTasks = `-- name: IsolationProbeTasks :many
SELECT id, team_id, description, status, created_at, updated_at, public_id
FROM tasks
ORDER BY created_at ASC, id ASC
LIMIT $1
`

// Deliberately omits a team predicate: FORCE RLS is the isolation mechanism
// under proof. Keep this query bounded and out of production service paths.
func (q *Queries) IsolationProbeTasks(ctx context.Context, limit int32) ([]Task, error) {
	rows, err := q.db.Query(ctx, isolationProbeTasks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET description = $2,
    status = $3,
    updated_at = NOW()
WHERE public_id = $1
RETURNING id, team_id, description, status, created_at, updated_at, public_id
`

type UpdateTaskParams struct {
	PublicID    uuid.UUID `json:"public_id"`
	Description string    `json:"description"`
	Status      string    `json:"status"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask, arg.PublicID, arg.Description, arg.Status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicID,
	)
	return i, err
}
