// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package tenantdb

import (
	"context"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (team_id, description, status)
VALUES ($1, $2, $3)
RETURNING id, team_id, description, status, created_at, updated_at, public_id
`

type CreateTaskParams struct {
	TeamID      int64  `json:"team_id"`
	Description string `json:"description"`
	Status      string `json:"status"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask, arg.TeamID, arg.Description, arg.Status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicID,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :one
DELETE FROM tasks
WHERE id = $1 AND team_id = $2
RETURNING id, team_id, description, status, created_at, updated_at, public_id
`

type DeleteTaskParams struct {
	ID     int64 `json:"id"`
	TeamID int64 `json:"team_id"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, deleteTask, arg.ID, arg.TeamID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicID,
	)
	return i, err
}

const getTasks = `-- name: GetTasks :many
SELECT tasks.id, tasks.team_id, tasks.description, tasks.status, tasks.created_at, tasks.updated_at, tasks.public_id
FROM tasks
JOIN teams ON teams.id = tasks.team_id
WHERE teams.id = $1
ORDER BY tasks.created_at ASC, tasks.id ASC
LIMIT $2
`

type GetTasksParams struct {
	TeamID int64 `json:"team_id"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) GetTasks(ctx context.Context, arg GetTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasks, arg.TeamID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET description = $3,
    status = $4,
    updated_at = NOW()
WHERE id = $1 AND team_id = $2
RETURNING id, team_id, description, status, created_at, updated_at, public_id
`

type UpdateTaskParams struct {
	ID          int64  `json:"id"`
	TeamID      int64  `json:"team_id"`
	Description string `json:"description"`
	Status      string `json:"status"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.TeamID,
		arg.Description,
		arg.Status,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicID,
	)
	return i, err
}
