// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package tenantdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assigneeIsMember = `-- name: AssigneeIsMember :one
SELECT EXISTS (
    SELECT 1 FROM team_members
    WHERE team_id = NULLIF(current_setting('app.team_id', true), '')::BIGINT
      AND user_public_id = $1
)
`

func (q *Queries) AssigneeIsMember(ctx context.Context, userPublicID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, assigneeIsMember, userPublicID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (team_id, description, status, assignee_public_id, start_date, due_date, details)
VALUES (NULLIF(current_setting('app.team_id', true), '')::BIGINT, $1, $2, $3, $4, $5, $6)
RETURNING id, team_id, description, status, created_at, updated_at, public_id, assignee_public_id, start_date, due_date, details
`

type CreateTaskParams struct {
	Description      string             `json:"description"`
	Status           string             `json:"status"`
	AssigneePublicID pgtype.UUID        `json:"assignee_public_id"`
	StartDate        pgtype.Timestamptz `json:"start_date"`
	DueDate          pgtype.Timestamptz `json:"due_date"`
	Details          string             `json:"details"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.Description,
		arg.Status,
		arg.AssigneePublicID,
		arg.StartDate,
		arg.DueDate,
		arg.Details,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicID,
		&i.AssigneePublicID,
		&i.StartDate,
		&i.DueDate,
		&i.Details,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :one
DELETE FROM tasks
WHERE public_id = $1
RETURNING id, team_id, description, status, created_at, updated_at, public_id, assignee_public_id, start_date, due_date, details
`

func (q *Queries) DeleteTask(ctx context.Context, publicID uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, deleteTask, publicID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicID,
		&i.AssigneePublicID,
		&i.StartDate,
		&i.DueDate,
		&i.Details,
	)
	return i, err
}

const getTasks = `-- name: GetTasks :many
SELECT tasks.id, tasks.team_id, tasks.description, tasks.status, tasks.created_at, tasks.updated_at, tasks.public_id, tasks.assignee_public_id, tasks.start_date, tasks.due_date, tasks.details
FROM tasks
ORDER BY tasks.created_at ASC, tasks.id ASC
LIMIT $1
`

func (q *Queries) GetTasks(ctx context.Context, limit int32) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublicID,
			&i.AssigneePublicID,
			&i.StartDate,
			&i.DueDate,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksAfter = `-- name: GetTasksAfter :many
SELECT tasks.id, tasks.team_id, tasks.description, tasks.status, tasks.created_at, tasks.updated_at, tasks.public_id, tasks.assignee_public_id, tasks.start_date, tasks.due_date, tasks.details
FROM tasks
WHERE (tasks.created_at, tasks.public_id) > ($1, $2::uuid)
ORDER BY tasks.created_at ASC, tasks.public_id ASC
LIMIT $3
`

type GetTasksAfterParams struct {
	AfterCreatedAt time.Time `json:"after_created_at"`
	AfterPublicID  uuid.UUID `json:"after_public_id"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) GetTasksAfter(ctx context.Context, arg GetTasksAfterParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasksAfter, arg.AfterCreatedAt, arg.AfterPublicID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublicID,
			&i.AssigneePublicID,
			&i.StartDate,
			&i.DueDate,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksBefore = `-- name: GetTasksBefore :many
SELECT tasks.id, tasks.team_id, tasks.description, tasks.status, tasks.created_at, tasks.updated_at, tasks.public_id, tasks.assignee_public_id, tasks.start_date, tasks.due_date, tasks.details
FROM tasks
WHERE (tasks.created_at, tasks.public_id) < ($1, $2::uuid)
ORDER BY tasks.created_at DESC, tasks.public_id DESC
LIMIT $3
`

type GetTasksBeforeParams struct {
	BeforeCreatedAt time.Time `json:"before_created_at"`
	BeforePublicID  uuid.UUID `json:"before_public_id"`
	Limit           int32     `json:"limit"`
}

func (q *Queries) GetTasksBefore(ctx context.Context, arg GetTasksBeforeParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasksBefore, arg.BeforeCreatedAt, arg.BeforePublicID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublicID,
			&i.AssigneePublicID,
			&i.StartDate,
			&i.DueDate,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isolationProbeTasks = `-- name: IsolationProbeTasks :many
SELECT id, team_id, description, status, created_at, updated_at, public_id, assignee_public_id, start_date, due_date, details
FROM tasks
ORDER BY created_at ASC, id ASC
LIMIT $1
`

// Deliberately omits a team predicate: FORCE RLS is the isolation mechanism
// under proof. Keep this query bounded and out of production service paths.
func (q *Queries) IsolationProbeTasks(ctx context.Context, limit int32) ([]Task, error) {
	rows, err := q.db.Query(ctx, isolationProbeTasks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublicID,
			&i.AssigneePublicID,
			&i.StartDate,
			&i.DueDate,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unassignTask = `-- name: UnassignTask :one
UPDATE tasks
SET assignee_public_id = NULL,
    updated_at = NOW()
WHERE public_id = $1
RETURNING id, team_id, description, status, created_at, updated_at, public_id, assignee_public_id, start_date, due_date, details
`

func (q *Queries) UnassignTask(ctx context.Context, publicID uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, unassignTask, publicID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicID,
		&i.AssigneePublicID,
		&i.StartDate,
		&i.DueDate,
		&i.Details,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET description = $2,
    status = $3,
    details = CASE WHEN $4::boolean THEN $5::text ELSE details END,
    assignee_public_id = CASE WHEN $6::boolean THEN $7::uuid ELSE assignee_public_id END,
    start_date = CASE WHEN $8::boolean THEN $9::timestamptz ELSE start_date END,
    due_date = CASE WHEN $10::boolean THEN $11::timestamptz ELSE due_date END,
    updated_at = NOW()
WHERE public_id = $1
RETURNING id, team_id, description, status, created_at, updated_at, public_id, assignee_public_id, start_date, due_date, details
`

type UpdateTaskParams struct {
	PublicID         uuid.UUID          `json:"public_id"`
	Description      string             `json:"description"`
	Status           string             `json:"status"`
	SetDetails       bool               `json:"set_details"`
	Details          string             `json:"details"`
	SetAssignee      bool               `json:"set_assignee"`
	AssigneePublicID pgtype.UUID        `json:"assignee_public_id"`
	SetStartDate     bool               `json:"set_start_date"`
	StartDate        pgtype.Timestamptz `json:"start_date"`
	SetDueDate       bool               `json:"set_due_date"`
	DueDate          pgtype.Timestamptz `json:"due_date"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.PublicID,
		arg.Description,
		arg.Status,
		arg.SetDetails,
		arg.Details,
		arg.SetAssignee,
		arg.AssigneePublicID,
		arg.SetStartDate,
		arg.StartDate,
		arg.SetDueDate,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicID,
		&i.AssigneePublicID,
		&i.StartDate,
		&i.DueDate,
		&i.Details,
	)
	return i, err
}
