// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_keys.sql

package tenantdb

import (
	"context"

	"github.com/google/uuid"
)

const appendTeamKeyWrap = `-- name: AppendTeamKeyWrap :one
SELECT id, team_id, version, status, algorithm, wraps, created_by, created_at
FROM synodus_append_team_key_wrap($1, $2, $3, $4)
`

type AppendTeamKeyWrapParams struct {
	CandidateTeamID  int64     `json:"candidate_team_id"`
	CandidateVersion int32     `json:"candidate_version"`
	KeyWrap          []byte    `json:"key_wrap"`
	CallerUserID     uuid.UUID `json:"caller_user_id"`
}

func (q *Queries) AppendTeamKeyWrap(ctx context.Context, arg AppendTeamKeyWrapParams) (TeamKey, error) {
	row := q.db.QueryRow(ctx, appendTeamKeyWrap,
		arg.CandidateTeamID,
		arg.CandidateVersion,
		arg.KeyWrap,
		arg.CallerUserID,
	)
	var i TeamKey
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Version,
		&i.Status,
		&i.Algorithm,
		&i.Wraps,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createTeamKeyVersion = `-- name: CreateTeamKeyVersion :one
SELECT id, team_id, version, status, algorithm, wraps, created_by, created_at
FROM synodus_commit_team_key($1, $2, $3, $4)
`

type CreateTeamKeyVersionParams struct {
	CandidateTeamID int64     `json:"candidate_team_id"`
	KeyAlgorithm    string    `json:"key_algorithm"`
	KeyWraps        []byte    `json:"key_wraps"`
	KeyCreatedBy    uuid.UUID `json:"key_created_by"`
}

func (q *Queries) CreateTeamKeyVersion(ctx context.Context, arg CreateTeamKeyVersionParams) (TeamKey, error) {
	row := q.db.QueryRow(ctx, createTeamKeyVersion,
		arg.CandidateTeamID,
		arg.KeyAlgorithm,
		arg.KeyWraps,
		arg.KeyCreatedBy,
	)
	var i TeamKey
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Version,
		&i.Status,
		&i.Algorithm,
		&i.Wraps,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listTeamKeysForTeam = `-- name: ListTeamKeysForTeam :many
SELECT id, team_id, version, status, algorithm, wraps, created_by, created_at
FROM team_keys
WHERE team_id = $1
ORDER BY version DESC
LIMIT $2
`

type ListTeamKeysForTeamParams struct {
	TeamID int64 `json:"team_id"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListTeamKeysForTeam(ctx context.Context, arg ListTeamKeysForTeamParams) ([]TeamKey, error) {
	rows, err := q.db.Query(ctx, listTeamKeysForTeam, arg.TeamID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamKey
	for rows.Next() {
		var i TeamKey
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Version,
			&i.Status,
			&i.Algorithm,
			&i.Wraps,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
