// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_ai_settings.sql

package tenantdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getTeamAISettings = `-- name: GetTeamAISettings :one
SELECT endpoint_url, model, api_token FROM team_ai_settings
WHERE team_id = NULLIF(current_setting('app.team_id', true), '')::BIGINT
`

type GetTeamAISettingsRow struct {
	EndpointUrl string `json:"endpoint_url"`
	Model       string `json:"model"`
	ApiToken    string `json:"api_token"`
}

func (q *Queries) GetTeamAISettings(ctx context.Context) (GetTeamAISettingsRow, error) {
	row := q.db.QueryRow(ctx, getTeamAISettings)
	var i GetTeamAISettingsRow
	err := row.Scan(&i.EndpointUrl, &i.Model, &i.ApiToken)
	return i, err
}

const listAIChatMessages = `-- name: ListAIChatMessages :many
SELECT public_id, sender_user_public_id, message, created_at FROM chat_messages
WHERE team_id = NULLIF(current_setting('app.team_id', true), '')::BIGINT
    AND deleted_at IS NULL AND btrim(message) <> ''
    AND created_at >= $1::timestamptz
    AND created_at <= $2::timestamptz
ORDER BY created_at, public_id
LIMIT $3
`

type ListAIChatMessagesParams struct {
	FromTime time.Time `json:"from_time"`
	ToTime   time.Time `json:"to_time"`
	Limit    int32     `json:"limit"`
}

type ListAIChatMessagesRow struct {
	PublicID           uuid.UUID `json:"public_id"`
	SenderUserPublicID uuid.UUID `json:"sender_user_public_id"`
	Message            string    `json:"message"`
	CreatedAt          time.Time `json:"created_at"`
}

func (q *Queries) ListAIChatMessages(ctx context.Context, arg ListAIChatMessagesParams) ([]ListAIChatMessagesRow, error) {
	rows, err := q.db.Query(ctx, listAIChatMessages, arg.FromTime, arg.ToTime, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAIChatMessagesRow
	for rows.Next() {
		var i ListAIChatMessagesRow
		if err := rows.Scan(
			&i.PublicID,
			&i.SenderUserPublicID,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveTeamAISettings = `-- name: SaveTeamAISettings :one
INSERT INTO team_ai_settings (team_id, endpoint_url, model, api_token)
VALUES (NULLIF(current_setting('app.team_id', true), '')::BIGINT,
    $1, $2, $3)
ON CONFLICT (team_id) DO UPDATE SET endpoint_url = EXCLUDED.endpoint_url,
    model = EXCLUDED.model,
    api_token = CASE WHEN EXCLUDED.api_token = '' THEN team_ai_settings.api_token ELSE EXCLUDED.api_token END
RETURNING endpoint_url, model, api_token
`

type SaveTeamAISettingsParams struct {
	EndpointUrl string `json:"endpoint_url"`
	Model       string `json:"model"`
	ApiToken    string `json:"api_token"`
}

type SaveTeamAISettingsRow struct {
	EndpointUrl string `json:"endpoint_url"`
	Model       string `json:"model"`
	ApiToken    string `json:"api_token"`
}

func (q *Queries) SaveTeamAISettings(ctx context.Context, arg SaveTeamAISettingsParams) (SaveTeamAISettingsRow, error) {
	row := q.db.QueryRow(ctx, saveTeamAISettings, arg.EndpointUrl, arg.Model, arg.ApiToken)
	var i SaveTeamAISettingsRow
	err := row.Scan(&i.EndpointUrl, &i.Model, &i.ApiToken)
	return i, err
}
