// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package tenantdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addTeamContributor = `-- name: AddTeamContributor :one
SELECT team_id, user_public_id, role, created_at, updated_at
FROM add_team_contributor($1)
`

func (q *Queries) AddTeamContributor(ctx context.Context, email string) (TeamMember, error) {
	row := q.db.QueryRow(ctx, addTeamContributor, email)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.UserPublicID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug, created_at, updated_at, public_id, is_quarantine
`

type CreateTeamParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.Name, arg.Slug)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicID,
		&i.IsQuarantine,
	)
	return i, err
}

const createTeamWithCreator = `-- name: CreateTeamWithCreator :one
SELECT id, name, slug, created_at, updated_at, public_id, is_quarantine
FROM create_team_with_creator($1, $2)
`

type CreateTeamWithCreatorParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateTeamWithCreator(ctx context.Context, arg CreateTeamWithCreatorParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeamWithCreator, arg.Name, arg.Slug)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicID,
		&i.IsQuarantine,
	)
	return i, err
}

const getCurrentTeamRole = `-- name: GetCurrentTeamRole :one
SELECT role FROM team_members
WHERE team_id = $1
  AND user_public_id = synodus_app_user_public_id()
`

func (q *Queries) GetCurrentTeamRole(ctx context.Context, teamID int64) (string, error) {
	row := q.db.QueryRow(ctx, getCurrentTeamRole, teamID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getTeams = `-- name: GetTeams :many
SELECT id, name, slug, created_at, updated_at, public_id, is_quarantine
FROM teams
ORDER BY created_at ASC, id ASC
LIMIT $1
`

func (q *Queries) GetTeams(ctx context.Context, limit int32) ([]Team, error) {
	rows, err := q.db.Query(ctx, getTeams, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublicID,
			&i.IsQuarantine,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamsAfter = `-- name: GetTeamsAfter :many
SELECT id, name, slug, created_at, updated_at, public_id, is_quarantine
FROM teams
WHERE NOT is_quarantine
  AND (created_at, public_id) > ($1, $2::uuid)
ORDER BY created_at ASC, public_id ASC
LIMIT $3
`

type GetTeamsAfterParams struct {
	AfterCreatedAt time.Time `json:"after_created_at"`
	AfterPublicID  uuid.UUID `json:"after_public_id"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) GetTeamsAfter(ctx context.Context, arg GetTeamsAfterParams) ([]Team, error) {
	rows, err := q.db.Query(ctx, getTeamsAfter, arg.AfterCreatedAt, arg.AfterPublicID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublicID,
			&i.IsQuarantine,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamsBefore = `-- name: GetTeamsBefore :many
SELECT id, name, slug, created_at, updated_at, public_id, is_quarantine
FROM teams
WHERE NOT is_quarantine
  AND (created_at, public_id) < ($1, $2::uuid)
ORDER BY created_at DESC, public_id DESC
LIMIT $3
`

type GetTeamsBeforeParams struct {
	BeforeCreatedAt time.Time `json:"before_created_at"`
	BeforePublicID  uuid.UUID `json:"before_public_id"`
	Limit           int32     `json:"limit"`
}

func (q *Queries) GetTeamsBefore(ctx context.Context, arg GetTeamsBeforeParams) ([]Team, error) {
	rows, err := q.db.Query(ctx, getTeamsBefore, arg.BeforeCreatedAt, arg.BeforePublicID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublicID,
			&i.IsQuarantine,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembersAfter = `-- name: ListTeamMembersAfter :many
SELECT user_public_id, role, created_at
FROM team_members
WHERE team_id = nullif(current_setting('app.team_id', true), '')::bigint
ORDER BY created_at, user_public_id
LIMIT $1
`

type ListTeamMembersAfterRow struct {
	UserPublicID uuid.UUID `json:"user_public_id"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) ListTeamMembersAfter(ctx context.Context, limit int32) ([]ListTeamMembersAfterRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembersAfter, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMembersAfterRow
	for rows.Next() {
		var i ListTeamMembersAfterRow
		if err := rows.Scan(&i.UserPublicID, &i.Role, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveTeamContext = `-- name: ResolveTeamContext :one
SELECT teams.id, teams.public_id
FROM teams
JOIN team_members
  ON team_members.team_id = teams.id
WHERE teams.public_id = $1
  AND team_members.user_public_id = $2
  AND NOT teams.is_quarantine
`

type ResolveTeamContextParams struct {
	PublicID     uuid.UUID `json:"public_id"`
	UserPublicID uuid.UUID `json:"user_public_id"`
}

type ResolveTeamContextRow struct {
	ID       int64     `json:"id"`
	PublicID uuid.UUID `json:"public_id"`
}

func (q *Queries) ResolveTeamContext(ctx context.Context, arg ResolveTeamContextParams) (ResolveTeamContextRow, error) {
	row := q.db.QueryRow(ctx, resolveTeamContext, arg.PublicID, arg.UserPublicID)
	var i ResolveTeamContextRow
	err := row.Scan(&i.ID, &i.PublicID)
	return i, err
}

const revalidateTeamAuthorization = `-- name: RevalidateTeamAuthorization :one
SELECT teams.public_id, team_members.role
FROM teams
JOIN team_members ON team_members.team_id = teams.id
WHERE teams.id = nullif(current_setting('app.team_id', true), '')::bigint
  AND teams.public_id = $1
  AND team_members.user_public_id = $2
  AND NOT teams.is_quarantine
`

type RevalidateTeamAuthorizationParams struct {
	TeamPublicID uuid.UUID `json:"team_public_id"`
	UserPublicID uuid.UUID `json:"user_public_id"`
}

type RevalidateTeamAuthorizationRow struct {
	PublicID uuid.UUID `json:"public_id"`
	Role     string    `json:"role"`
}

func (q *Queries) RevalidateTeamAuthorization(ctx context.Context, arg RevalidateTeamAuthorizationParams) (RevalidateTeamAuthorizationRow, error) {
	row := q.db.QueryRow(ctx, revalidateTeamAuthorization, arg.TeamPublicID, arg.UserPublicID)
	var i RevalidateTeamAuthorizationRow
	err := row.Scan(&i.PublicID, &i.Role)
	return i, err
}
