CREATE TABLE team_shared_keys (
    team_id BIGINT NOT NULL CONSTRAINT team_shared_keys_team_fk REFERENCES teams(id) ON DELETE CASCADE,
    user_id UUID NOT NULL CONSTRAINT team_shared_keys_user_fk REFERENCES public.users(user_id) ON DELETE CASCADE,
    encrypted_key TEXT NOT NULL,
    key_version INT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (team_id, user_id, key_version)
);

CREATE TABLE files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT files_pk PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid() CONSTRAINT files_public_id_unique UNIQUE,
    team_id BIGINT NOT NULL CONSTRAINT files_team_fk REFERENCES teams(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    size BIGINT NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    object_key VARCHAR(1024) NOT NULL,
    iv BYTEA NOT NULL,
    key_version INT NOT NULL,
    uploaded_by UUID NOT NULL CONSTRAINT files_user_fk REFERENCES public.users(user_id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ
);

ALTER TABLE team_shared_keys OWNER TO synodus_owner;
ALTER TABLE files OWNER TO synodus_owner;
ALTER SEQUENCE files_id_seq OWNER TO synodus_owner;

ALTER TABLE team_shared_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_shared_keys FORCE ROW LEVEL SECURITY;
ALTER TABLE files ENABLE ROW LEVEL SECURITY;
ALTER TABLE files FORCE ROW LEVEL SECURITY;

CREATE POLICY team_shared_keys_owner_maintenance ON team_shared_keys
    FOR ALL TO synodus_owner USING (true) WITH CHECK (true);
CREATE POLICY files_owner_maintenance ON files
    FOR ALL TO synodus_owner USING (true) WITH CHECK (true);

-- Runtime RLS: only members of the team can view/update/insert/delete team keys or files
CREATE POLICY team_shared_keys_runtime_access ON team_shared_keys
    FOR ALL TO synodus_runtime
    USING (
        team_id = NULLIF(current_setting('app.team_id', true), '')::BIGINT
        AND synodus_has_team_membership(team_id)
    )
    WITH CHECK (
        team_id = NULLIF(current_setting('app.team_id', true), '')::BIGINT
        AND synodus_has_team_membership(team_id)
    );

CREATE POLICY files_runtime_access ON files
    FOR ALL TO synodus_runtime
    USING (
        team_id = NULLIF(current_setting('app.team_id', true), '')::BIGINT
        AND synodus_has_team_membership(team_id)
    )
    WITH CHECK (
        team_id = NULLIF(current_setting('app.team_id', true), '')::BIGINT
        AND synodus_has_team_membership(team_id)
    );

REVOKE ALL ON team_shared_keys, files FROM PUBLIC, synodus_runtime;
REVOKE ALL ON files_id_seq FROM PUBLIC, synodus_runtime;

GRANT SELECT, INSERT, UPDATE, DELETE ON team_shared_keys, files TO synodus_runtime;
GRANT USAGE, SELECT ON files_id_seq TO synodus_runtime;
