-- Team-key access requests: a member who joined after a key version was created
-- asks the team leader for access to files sealed under it. On approval the
-- leader's client re-wraps each missing version for the requester (RSA-OAEP) and
-- appends it via synodus_append_team_key_wrap.

CREATE TABLE team_key_access_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT team_key_access_requests_pk PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid()
        CONSTRAINT team_key_access_requests_public_id_unique UNIQUE,
    team_id BIGINT NOT NULL
        CONSTRAINT team_key_access_requests_team_fk
        REFERENCES teams(id) ON DELETE RESTRICT,
    requested_by UUID NOT NULL
        CONSTRAINT team_key_access_requests_requester_fk
        REFERENCES public.users(user_id) ON DELETE RESTRICT,
    status TEXT NOT NULL DEFAULT 'pending'
        CONSTRAINT team_key_access_requests_status_check
        CHECK (status IN ('pending', 'granted', 'denied')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    decided_by UUID
        CONSTRAINT team_key_access_requests_decider_fk
        REFERENCES public.users(user_id) ON DELETE RESTRICT,
    decided_at TIMESTAMPTZ,
    CONSTRAINT team_key_access_requests_decision_check CHECK (
        (status = 'pending' AND decided_at IS NULL AND decided_by IS NULL) OR
        (status IN ('granted', 'denied') AND decided_at IS NOT NULL AND decided_by IS NOT NULL)
    )
);

CREATE INDEX team_key_access_requests_team_status_idx
    ON team_key_access_requests (team_id, status, created_at DESC);
CREATE UNIQUE INDEX team_key_access_requests_pending_unique
    ON team_key_access_requests (team_id, requested_by)
    WHERE status = 'pending';

ALTER TABLE team_key_access_requests OWNER TO synodus_owner;
ALTER SEQUENCE team_key_access_requests_id_seq OWNER TO synodus_owner;

-- Member re-wrap endpoint: a member already wrapped in a version (which proves
-- they can unwrap it) may append a copy of the team symmetric key sealed with
-- another current member's public key. Duplicate and invalid callers no-op.
CREATE FUNCTION synodus_append_team_key_wrap(
    candidate_team_id BIGINT,
    candidate_version INT,
    key_wrap JSONB,
    caller_user_id UUID
)
RETURNS SETOF team_keys
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path FROM CURRENT
AS $$
DECLARE
    result team_keys%ROWTYPE;
BEGIN
    IF NOT synodus_has_team_membership(candidate_team_id)
       OR NOT EXISTS (
            SELECT 1 FROM team_keys
            WHERE team_id = candidate_team_id AND version = candidate_version
              AND wraps @> jsonb_build_array(jsonb_build_object('user_id', caller_user_id))
       ) THEN
        RETURN;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM team_members
        WHERE team_id = candidate_team_id AND user_public_id = (key_wrap ->> 'user_id')::uuid
    ) THEN
        RETURN;
    END IF;
    IF EXISTS (
        SELECT 1 FROM team_keys
        WHERE team_id = candidate_team_id AND version = candidate_version
          AND wraps @> jsonb_build_array(key_wrap)
    ) THEN
        RETURN QUERY SELECT id, team_id, version, status, algorithm, wraps, created_by, created_at
        FROM team_keys
        WHERE team_id = candidate_team_id AND version = candidate_version;
        RETURN;
    END IF;
    RETURN QUERY
    UPDATE team_keys
    SET wraps = wraps || jsonb_build_array(key_wrap)
    WHERE team_id = candidate_team_id AND version = candidate_version
    RETURNING id, team_id, version, status, algorithm, wraps, created_by, created_at;
END;
$$;
ALTER FUNCTION synodus_append_team_key_wrap(BIGINT, INT, JSONB, UUID) OWNER TO synodus_owner;
REVOKE ALL ON FUNCTION synodus_append_team_key_wrap(BIGINT, INT, JSONB, UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION synodus_append_team_key_wrap(BIGINT, INT, JSONB, UUID) TO synodus_runtime;

ALTER TABLE team_key_access_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_key_access_requests FORCE ROW LEVEL SECURITY;

CREATE POLICY team_key_access_requests_owner_maintenance ON team_key_access_requests
    FOR ALL TO synodus_owner USING (true) WITH CHECK (true);

-- Runtime: team members see and file team-scoped requests; who may decide is
-- enforced by the team-application permission layer, not row policy.
CREATE POLICY team_key_access_requests_runtime_access ON team_key_access_requests
    FOR ALL TO synodus_runtime
    USING (
        team_id = NULLIF(current_setting('app.team_id', true), '')::BIGINT
        AND synodus_has_team_membership(team_id)
    )
    WITH CHECK (
        team_id = NULLIF(current_setting('app.team_id', true), '')::BIGINT
        AND synodus_has_team_membership(team_id)
    );

REVOKE ALL ON team_key_access_requests FROM PUBLIC, synodus_runtime;
REVOKE ALL ON team_key_access_requests_id_seq FROM PUBLIC, synodus_runtime;
GRANT SELECT, INSERT, UPDATE ON team_key_access_requests TO synodus_runtime;
GRANT USAGE, SELECT ON team_key_access_requests_id_seq TO synodus_runtime;