CREATE TABLE resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT resources_pk PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid() CONSTRAINT resources_public_id_unique UNIQUE,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(64) NOT NULL,
    kind TEXT NOT NULL CONSTRAINT resources_kind_check
        CHECK (kind IN ('gpu', 'instrument', 'room', 'workstation')),
    location VARCHAR(255) NOT NULL DEFAULT '',
    enabled BOOLEAN NOT NULL DEFAULT true,
    availability JSONB NOT NULL DEFAULT '[]'::jsonb
        CONSTRAINT resources_availability_array CHECK (jsonb_typeof(availability) = 'array'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT resources_code_normalized CHECK (code = upper(btrim(code)))
);

CREATE UNIQUE INDEX resources_code_unique ON resources (upper(btrim(code)));

CREATE TABLE resource_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT resource_requests_pk PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid() CONSTRAINT resource_requests_public_id_unique UNIQUE,
    resource_id BIGINT NOT NULL CONSTRAINT resource_requests_resource_fk
        REFERENCES resources(id) ON DELETE RESTRICT,
    team_id BIGINT NOT NULL CONSTRAINT resource_requests_team_fk
        REFERENCES teams(id) ON DELETE RESTRICT,
    requested_by UUID NOT NULL CONSTRAINT resource_requests_user_fk
        REFERENCES public.users(user_id) ON DELETE RESTRICT,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    purpose VARCHAR(1000) NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CONSTRAINT resource_requests_status_check
        CHECK (status IN ('pending', 'approved', 'rejected')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    decided_at TIMESTAMPTZ,
    CONSTRAINT resource_requests_interval_check CHECK (start_time < end_time),
    CONSTRAINT resource_requests_decision_check CHECK (
        (status = 'pending' AND decided_at IS NULL) OR
        (status IN ('approved', 'rejected') AND decided_at IS NOT NULL)
    )
);

CREATE INDEX resource_requests_resource_interval_idx
    ON resource_requests (resource_id, start_time, end_time)
    WHERE status = 'approved';
CREATE INDEX resource_requests_team_created_idx
    ON resource_requests (team_id, created_at DESC);
CREATE INDEX resource_requests_status_created_idx
    ON resource_requests (status, created_at DESC);

ALTER TABLE resources OWNER TO synodus_owner;
ALTER TABLE resource_requests OWNER TO synodus_owner;
ALTER SEQUENCE resources_id_seq OWNER TO synodus_owner;
ALTER SEQUENCE resource_requests_id_seq OWNER TO synodus_owner;

ALTER TABLE resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE resources FORCE ROW LEVEL SECURITY;
ALTER TABLE resource_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE resource_requests FORCE ROW LEVEL SECURITY;

CREATE FUNCTION synodus_has_organization_membership()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path FROM CURRENT
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.users AS app_user
        JOIN public.org_user AS membership ON membership.user_id = app_user.id
        JOIN public.orgs AS organization ON organization.id = membership.org_id
        WHERE app_user.user_id = synodus_app_user_public_id()
          AND app_user.deleted_at IS NULL
          AND organization.schema_name = current_schema()
          AND organization.deleted_at IS NULL
          AND organization.lifecycle_state = 'active'
    );
$$;
ALTER FUNCTION synodus_has_organization_membership() OWNER TO synodus_owner;

CREATE FUNCTION synodus_current_organization_role()
RETURNS TEXT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path FROM CURRENT
AS $$
    SELECT membership.role
    FROM public.users AS app_user
    JOIN public.org_user AS membership ON membership.user_id = app_user.id
    JOIN public.orgs AS organization ON organization.id = membership.org_id
    WHERE app_user.user_id = synodus_app_user_public_id()
      AND organization.schema_name = current_schema()
      AND app_user.deleted_at IS NULL
      AND organization.deleted_at IS NULL;
$$;
ALTER FUNCTION synodus_current_organization_role() OWNER TO synodus_owner;

CREATE FUNCTION synodus_user_display_name(candidate UUID)
RETURNS TEXT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path FROM CURRENT
AS $$
    SELECT display_name FROM public.users
    WHERE user_id = candidate AND deleted_at IS NULL;
$$;
ALTER FUNCTION synodus_user_display_name(UUID) OWNER TO synodus_owner;

CREATE POLICY resources_owner_maintenance ON resources
    FOR ALL TO synodus_owner USING (true) WITH CHECK (true);
CREATE POLICY resource_requests_owner_maintenance ON resource_requests
    FOR ALL TO synodus_owner USING (true) WITH CHECK (true);
CREATE POLICY resources_runtime_access ON resources
    FOR ALL TO synodus_runtime
    USING (synodus_has_organization_membership())
    WITH CHECK (synodus_has_organization_membership());
CREATE POLICY resource_requests_runtime_access ON resource_requests
    FOR ALL TO synodus_runtime
    USING (synodus_has_organization_membership())
    WITH CHECK (synodus_has_organization_membership());
-- Team identity (name/public id) is organization metadata. Team content remains
-- protected by team_members/tasks policies and exact-team authorization.
CREATE POLICY teams_runtime_organization_select ON teams
    FOR SELECT TO synodus_runtime
    USING (NOT is_quarantine AND synodus_has_organization_membership());

REVOKE ALL ON resources, resource_requests FROM PUBLIC, synodus_runtime;
REVOKE ALL ON resources_id_seq, resource_requests_id_seq FROM PUBLIC, synodus_runtime;
REVOKE ALL ON FUNCTION synodus_has_organization_membership() FROM PUBLIC;
REVOKE ALL ON FUNCTION synodus_current_organization_role() FROM PUBLIC;
REVOKE ALL ON FUNCTION synodus_user_display_name(UUID) FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON resources, resource_requests TO synodus_runtime;
GRANT USAGE, SELECT ON resources_id_seq, resource_requests_id_seq TO synodus_runtime;
GRANT EXECUTE ON FUNCTION synodus_has_organization_membership() TO synodus_runtime;
GRANT EXECUTE ON FUNCTION synodus_current_organization_role() TO synodus_runtime;
GRANT EXECUTE ON FUNCTION synodus_user_display_name(UUID) TO synodus_runtime;
