CREATE TABLE team_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT team_keys_pk PRIMARY KEY,
    team_id BIGINT NOT NULL CONSTRAINT team_keys_team_fk REFERENCES teams(id) ON DELETE CASCADE,
    version INT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'active',
    algorithm VARCHAR(32) NOT NULL DEFAULT 'aes-256-gcm',
    wraps JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_by UUID NOT NULL CONSTRAINT team_keys_user_fk REFERENCES public.users(user_id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE team_keys ADD CONSTRAINT team_keys_team_version_unique UNIQUE (team_id, version);
CREATE INDEX team_keys_team_status_idx ON team_keys (team_id, status);

ALTER TABLE team_keys OWNER TO synodus_owner;
ALTER SEQUENCE team_keys_id_seq OWNER TO synodus_owner;

DROP TABLE team_shared_keys;

-- Owner-privileged rotation: supersede the active version and allocate the next
-- version number atomically, bypassing runtime RLS so new joiners can rotate too.
CREATE FUNCTION synodus_commit_team_key(candidate_team_id BIGINT, key_algorithm TEXT, key_wraps JSONB, key_created_by UUID)
RETURNS SETOF team_keys
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path FROM CURRENT
AS $$
DECLARE
    next_version INT;
BEGIN
    UPDATE team_keys SET status = 'superseded' WHERE team_id = candidate_team_id AND status = 'active';
    SELECT COALESCE(MAX(version), 0) + 1 INTO next_version FROM team_keys WHERE team_id = candidate_team_id;
    RETURN QUERY
    INSERT INTO team_keys (team_id, version, status, algorithm, wraps, created_by)
    VALUES (candidate_team_id, next_version, 'active', key_algorithm, key_wraps, key_created_by)
    RETURNING id, team_id, version, status, algorithm, wraps, created_by, created_at;
END;
$$;
ALTER FUNCTION synodus_commit_team_key(BIGINT, TEXT, JSONB, UUID) OWNER TO synodus_owner;
REVOKE ALL ON FUNCTION synodus_commit_team_key(BIGINT, TEXT, JSONB, UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION synodus_commit_team_key(BIGINT, TEXT, JSONB, UUID) TO synodus_runtime;

ALTER TABLE team_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_keys FORCE ROW LEVEL SECURITY;

CREATE POLICY team_keys_owner_maintenance ON team_keys
    FOR ALL TO synodus_owner USING (true) WITH CHECK (true);

-- Runtime RLS: team members see versions whose wraps include them; they may
-- create versions only when wrapped for themselves too (author keeps a copy).
CREATE POLICY team_keys_runtime_access ON team_keys
    FOR ALL TO synodus_runtime
    USING (
        team_id = NULLIF(current_setting('app.team_id', true), '')::BIGINT
        AND synodus_has_team_membership(team_id)
        AND wraps @> jsonb_build_array(jsonb_build_object('user_id', synodus_app_user_public_id()))
    )
    WITH CHECK (
        team_id = NULLIF(current_setting('app.team_id', true), '')::BIGINT
        AND synodus_has_team_membership(team_id)
        AND wraps @> jsonb_build_array(jsonb_build_object('user_id', synodus_app_user_public_id()))
    );

REVOKE ALL ON team_keys FROM PUBLIC, synodus_runtime;
REVOKE ALL ON team_keys_id_seq FROM PUBLIC, synodus_runtime;

GRANT SELECT, INSERT, UPDATE, DELETE ON team_keys TO synodus_runtime;
GRANT USAGE, SELECT ON team_keys_id_seq TO synodus_runtime;