CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT chat_messages_pk PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid() CONSTRAINT chat_messages_public_id_unique UNIQUE,
    team_id BIGINT NOT NULL CONSTRAINT chat_messages_team_fk REFERENCES teams(id) ON DELETE CASCADE,
    sender_user_public_id UUID NOT NULL CONSTRAINT chat_messages_sender_fk REFERENCES public.users(user_id) ON DELETE RESTRICT,
    reply_to_public_id UUID,
    mentions UUID[] NOT NULL DEFAULT '{}',
    message VARCHAR(4096) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT chat_messages_reply_fk FOREIGN KEY (reply_to_public_id) REFERENCES chat_messages(public_id) ON DELETE SET NULL
);

CREATE INDEX chat_messages_team_created_idx
    ON chat_messages (team_id, created_at DESC, public_id DESC);

ALTER TABLE chat_messages OWNER TO synodus_owner;
ALTER SEQUENCE chat_messages_id_seq OWNER TO synodus_owner;

ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_messages FORCE ROW LEVEL SECURITY;

CREATE POLICY chat_messages_owner_maintenance ON chat_messages
    FOR ALL TO synodus_owner USING (true) WITH CHECK (true);

CREATE POLICY chat_messages_runtime_access ON chat_messages
    FOR ALL TO synodus_runtime
    USING (
        team_id = NULLIF(current_setting('app.team_id', true), '')::BIGINT
        AND synodus_has_team_membership(team_id)
    )
    WITH CHECK (
        team_id = NULLIF(current_setting('app.team_id', true), '')::BIGINT
        AND synodus_has_team_membership(team_id)
    );

REVOKE ALL ON chat_messages FROM PUBLIC, synodus_runtime;
REVOKE ALL ON chat_messages_id_seq FROM PUBLIC, synodus_runtime;

GRANT SELECT, INSERT, UPDATE ON chat_messages TO synodus_runtime;
GRANT USAGE, SELECT ON chat_messages_id_seq TO synodus_runtime;
