CREATE TABLE tasks(
    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT tasks_pk PRIMARY KEY,

    team_id BIGINT
        CONSTRAINT tasks_team_fk
        REFERENCES teams(id)
        ON DELETE CASCADE,

    description TEXT NOT NULL,

    status TEXT NOT NULL DEFAULT 'todo' CHECK (status IN ('todo', 'in_progress', 'done')),

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);