CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT documents_pk PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid() CONSTRAINT documents_public_id_unique UNIQUE,
    team_id BIGINT NOT NULL CONSTRAINT documents_team_fk REFERENCES teams(id) ON DELETE CASCADE,
    canonical_state BYTEA NOT NULL DEFAULT ''::bytea,
    title VARCHAR(255) NOT NULL DEFAULT '',
    body_html TEXT NOT NULL DEFAULT '',
    last_updated_by UUID NOT NULL CONSTRAINT documents_last_updated_by_fk REFERENCES public.users(user_id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX documents_team_recent_idx ON documents (team_id, updated_at DESC, public_id DESC);

ALTER TABLE documents OWNER TO synodus_owner;
ALTER SEQUENCE documents_id_seq OWNER TO synodus_owner;
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents FORCE ROW LEVEL SECURITY;

CREATE POLICY documents_owner_maintenance ON documents
    FOR ALL TO synodus_owner USING (true) WITH CHECK (true);
CREATE POLICY documents_runtime_access ON documents
    FOR ALL TO synodus_runtime
    USING (team_id = NULLIF(current_setting('app.team_id', true), '')::BIGINT AND synodus_has_team_membership(team_id))
    WITH CHECK (team_id = NULLIF(current_setting('app.team_id', true), '')::BIGINT AND synodus_has_team_membership(team_id));

REVOKE ALL ON documents FROM PUBLIC, synodus_runtime;
REVOKE ALL ON documents_id_seq FROM PUBLIC, synodus_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON documents TO synodus_runtime;
GRANT USAGE, SELECT ON documents_id_seq TO synodus_runtime;
