CREATE TABLE teams (
    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT teams_pk PRIMARY KEY,

    name VARCHAR(255) NOT NULL
        CONSTRAINT teams_name_unique UNIQUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);