SQLC_VERSION := v1.31.1
GOLANGCI_LINT_VERSION := v2.12.2
GOSEC_VERSION := v2.28.0
GOVULNCHECK_VERSION := v1.6.0
GITLEAKS_VERSION := v8.29.1

SQLC := $(TOOLS_DIR)/sqlc/$(SQLC_VERSION)/sqlc
GOLANGCI_LINT := $(TOOLS_DIR)/golangci-lint/$(GOLANGCI_LINT_VERSION)/golangci-lint
GOSEC := $(TOOLS_DIR)/gosec/$(GOSEC_VERSION)/gosec
GOVULNCHECK := $(TOOLS_DIR)/govulncheck/$(GOVULNCHECK_VERSION)/govulncheck
GITLEAKS := $(TOOLS_DIR)/gitleaks/$(GITLEAKS_VERSION)/gitleaks
