// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package repository

import (
	"context"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (team_id, name)
VALUES ($1, $2)
RETURNING id, team_id, name, created_at
`

type CreateChannelParams struct {
	TeamID int64  `json:"team_id"`
	Name   string `json:"name"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel, arg.TeamID, arg.Name)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getDefaultChannelByTeamID = `-- name: GetDefaultChannelByTeamID :one
SELECT id, team_id, name, created_at
FROM channels
WHERE team_id = $1
  AND name = 'general'
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetDefaultChannelByTeamID(ctx context.Context, teamID int64) (Channel, error) {
	row := q.db.QueryRow(ctx, getDefaultChannelByTeamID, teamID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
