// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO chat_messages (channel_id, sender_id, reply_to_id, message)
VALUES ($1, $2, $3, $4)
RETURNING id, channel_id, sender_id, reply_to_id, message, created_at, deleted_at
`

type CreateChatMessageParams struct {
	ChannelID uuid.UUID   `json:"channel_id"`
	SenderID  int64       `json:"sender_id"`
	ReplyToID pgtype.UUID `json:"reply_to_id"`
	Message   string      `json:"message"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, createChatMessage,
		arg.ChannelID,
		arg.SenderID,
		arg.ReplyToID,
		arg.Message,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.SenderID,
		&i.ReplyToID,
		&i.Message,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getChatMessageByID = `-- name: GetChatMessageByID :one
SELECT
    id,
    channel_id,
    sender_id,
    reply_to_id,
    message,
    created_at,
    deleted_at
FROM chat_messages
WHERE id = $1
`

func (q *Queries) GetChatMessageByID(ctx context.Context, id uuid.UUID) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, getChatMessageByID, id)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.SenderID,
		&i.ReplyToID,
		&i.Message,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listChatMessages = `-- name: ListChatMessages :many
SELECT
    m.id,
    m.channel_id,
    m.sender_id,
    m.reply_to_id,
    CASE WHEN m.deleted_at IS NULL THEN m.message ELSE '' END AS message,
    m.created_at,
    m.deleted_at,
    u.name AS sender_name,
    u.avatar_url AS sender_avatar_url
FROM chat_messages m
INNER JOIN users u ON u.id = m.sender_id
WHERE m.channel_id = $1
  AND (
    $2::uuid IS NULL
    OR (m.created_at, m.id) < (
        SELECT cm.created_at, cm.id
        FROM chat_messages cm
        WHERE cm.id = $2
    )
  )
ORDER BY m.created_at DESC, m.id DESC
LIMIT $3
`

type ListChatMessagesParams struct {
	ChannelID    uuid.UUID   `json:"channel_id"`
	Before       pgtype.UUID `json:"before"`
	MessageLimit int32       `json:"message_limit"`
}

type ListChatMessagesRow struct {
	ID              uuid.UUID          `json:"id"`
	ChannelID       uuid.UUID          `json:"channel_id"`
	SenderID        int64              `json:"sender_id"`
	ReplyToID       pgtype.UUID        `json:"reply_to_id"`
	Message         string             `json:"message"`
	CreatedAt       time.Time          `json:"created_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	SenderName      string             `json:"sender_name"`
	SenderAvatarUrl pgtype.Text        `json:"sender_avatar_url"`
}

func (q *Queries) ListChatMessages(ctx context.Context, arg ListChatMessagesParams) ([]ListChatMessagesRow, error) {
	rows, err := q.db.Query(ctx, listChatMessages, arg.ChannelID, arg.Before, arg.MessageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatMessagesRow
	for rows.Next() {
		var i ListChatMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.SenderID,
			&i.ReplyToID,
			&i.Message,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.SenderName,
			&i.SenderAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteChatMessage = `-- name: SoftDeleteChatMessage :one
UPDATE chat_messages
SET deleted_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, channel_id, sender_id, reply_to_id, message, created_at, deleted_at
`

func (q *Queries) SoftDeleteChatMessage(ctx context.Context, id uuid.UUID) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, softDeleteChatMessage, id)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.SenderID,
		&i.ReplyToID,
		&i.Message,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
