// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: org_user.sql

package repository

import (
	"context"
)

const addUserToOrg = `-- name: AddUserToOrg :one
INSERT INTO org_user (org_id, user_id)
VALUES ($1, $2)
RETURNING org_id, user_id
`

type AddUserToOrgParams struct {
	OrgID  int64 `json:"org_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) AddUserToOrg(ctx context.Context, arg AddUserToOrgParams) (OrgUser, error) {
	row := q.db.QueryRow(ctx, addUserToOrg, arg.OrgID, arg.UserID)
	var i OrgUser
	err := row.Scan(&i.OrgID, &i.UserID)
	return i, err
}

const getNumberOfUsersInOrg = `-- name: GetNumberOfUsersInOrg :one
SELECT COUNT(*) FROM org_user
WHERE org_id = $1
`

func (q *Queries) GetNumberOfUsersInOrg(ctx context.Context, orgID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getNumberOfUsersInOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOrgsForUser = `-- name: GetOrgsForUser :many
SELECT o.id, o.public_id, o.name, o.schema_name, o.created_at, o.updated_at, o.deleted_at FROM orgs o
JOIN org_user ou ON o.id = ou.org_id
WHERE ou.user_id = $1
AND o.deleted_at IS NULL
`

func (q *Queries) GetOrgsForUser(ctx context.Context, userID int64) ([]Org, error) {
	rows, err := q.db.Query(ctx, getOrgsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Org
	for rows.Next() {
		var i Org
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Name,
			&i.SchemaName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersInOrg = `-- name: GetUsersInOrg :many
SELECT u.id, u.user_id, u.email, u.password_hash, u.display_name, u.created_at, u.updated_at, u.deleted_at FROM users u
JOIN org_user ou ON u.id = ou.user_id
WHERE ou.org_id = $1
AND u.deleted_at IS NULL
`

func (q *Queries) GetUsersInOrg(ctx context.Context, orgID int64) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersInOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.PasswordHash,
			&i.DisplayName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromOrg = `-- name: RemoveUserFromOrg :one
DELETE FROM org_user
WHERE org_id = $1
AND user_id = $2
RETURNING org_id, user_id
`

type RemoveUserFromOrgParams struct {
	OrgID  int64 `json:"org_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) RemoveUserFromOrg(ctx context.Context, arg RemoveUserFromOrgParams) (OrgUser, error) {
	row := q.db.QueryRow(ctx, removeUserFromOrg, arg.OrgID, arg.UserID)
	var i OrgUser
	err := row.Scan(&i.OrgID, &i.UserID)
	return i, err
}
