// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orgs.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createOrg = `-- name: CreateOrg :one
INSERT INTO orgs (name)
VALUES ($1)
RETURNING id, public_id, name, created_at, updated_at
`

func (q *Queries) CreateOrg(ctx context.Context, name string) (Org, error) {
	row := q.db.QueryRow(ctx, createOrg, name)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgID = `-- name: GetOrgID :one
SELECT id FROM orgs
WHERE public_id = $1
`

func (q *Queries) GetOrgID(ctx context.Context, publicID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getOrgID, publicID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getOrgName = `-- name: GetOrgName :one
SELECT name FROM orgs
WHERE id = $1
`

func (q *Queries) GetOrgName(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, getOrgName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getOrgs = `-- name: GetOrgs :many
SELECT name FROM orgs
`

func (q *Queries) GetOrgs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getOrgs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrg = `-- name: UpdateOrg :one
UPDATE orgs
SET name = $2, updated_at = NOW()
WHERE public_id = $1
RETURNING id, public_id, name, created_at, updated_at
`

type UpdateOrgParams struct {
	PublicID uuid.UUID `json:"public_id"`
	Name     string    `json:"name"`
}

func (q *Queries) UpdateOrg(ctx context.Context, arg UpdateOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, updateOrg, arg.PublicID, arg.Name)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
