// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orgs.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getOrgID = `-- name: GetOrgID :one
SELECT id FROM orgs
WHERE public_id = $1
`

func (q *Queries) GetOrgID(ctx context.Context, publicID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getOrgID, publicID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getOrgName = `-- name: GetOrgName :one
SELECT name FROM orgs
WHERE id = $1
`

func (q *Queries) GetOrgName(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, getOrgName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getOrgs = `-- name: GetOrgs :many
SELECT name FROM orgs
`

func (q *Queries) GetOrgs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getOrgs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
