// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package repository

import (
	"context"
	"time"
)

const blockSession = `-- name: BlockSession :exec
UPDATE sessions
SET is_blocked = true
WHERE refresh_token = $1
`

func (q *Queries) BlockSession(ctx context.Context, refreshToken string) error {
	_, err := q.db.Exec(ctx, blockSession, refreshToken)
	return err
}

const blockSessionsByUserID = `-- name: BlockSessionsByUserID :exec
UPDATE sessions
SET is_blocked = true
WHERE user_id = $1
  AND is_blocked = false
`

func (q *Queries) BlockSessionsByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, blockSessionsByUserID, userID)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, refresh_token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, refresh_token, is_blocked, expires_at, created_at
`

type CreateSessionParams struct {
	UserID       int64     `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.RefreshToken, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByRefreshToken = `-- name: GetSessionByRefreshToken :one
SELECT id, user_id, refresh_token, is_blocked, expires_at, created_at
FROM sessions
WHERE refresh_token = $1
LIMIT 1
`

func (q *Queries) GetSessionByRefreshToken(ctx context.Context, refreshToken string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshToken, refreshToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
