// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (team_id, description)
VALUES ($1, $2)
RETURNING id, team_id, description, created_at, updated_at
`

type CreateTaskParams struct {
	TeamID      pgtype.Int8 `json:"team_id"`
	Description string      `json:"description"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask, arg.TeamID, arg.Description)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTasks = `-- name: GetTasks :many
SELECT tasks.id, tasks.team_id, tasks.description, tasks.created_at, tasks.updated_at
FROM tasks
JOIN teams ON teams.id = tasks.team_id
WHERE teams.id = $1
ORDER BY tasks.created_at ASC
`

func (q *Queries) GetTasks(ctx context.Context, id int64) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasks, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
