// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addTeamMember = `-- name: AddTeamMember :one
INSERT INTO team_members (team_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING team_id, user_id, role, joined_at
`

type AddTeamMemberParams struct {
	TeamID int64    `json:"team_id"`
	UserID int64    `json:"user_id"`
	Role   TeamRole `json:"role"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, addTeamMember, arg.TeamID, arg.UserID, arg.Role)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const countTeamLeaders = `-- name: CountTeamLeaders :one
SELECT COUNT(*)::bigint AS count
FROM team_members
WHERE team_id = $1
  AND role = 'TEAM_LEADER'
`

func (q *Queries) CountTeamLeaders(ctx context.Context, teamID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamLeaders, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (org_id, name, description, created_by_user)
VALUES ($1, $2, $3, $4)
RETURNING id, public_id, org_id, name, description, created_by_user, created_at, updated_at
`

type CreateTeamParams struct {
	OrgID         int64       `json:"org_id"`
	Name          string      `json:"name"`
	Description   pgtype.Text `json:"description"`
	CreatedByUser int64       `json:"created_by_user"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.OrgID,
		arg.Name,
		arg.Description,
		arg.CreatedByUser,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.CreatedByUser,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByPublicID = `-- name: GetTeamByPublicID :one
SELECT
    id,
    public_id,
    org_id,
    name,
    description,
    created_by_user,
    created_at,
    updated_at
FROM teams
WHERE public_id = $1
`

func (q *Queries) GetTeamByPublicID(ctx context.Context, publicID uuid.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByPublicID, publicID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.CreatedByUser,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamMembership = `-- name: GetTeamMembership :one
SELECT team_id, user_id, role, joined_at
FROM team_members
WHERE team_id = $1
  AND user_id = $2
`

type GetTeamMembershipParams struct {
	TeamID int64 `json:"team_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetTeamMembership(ctx context.Context, arg GetTeamMembershipParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, getTeamMembership, arg.TeamID, arg.UserID)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT
    tm.team_id,
    tm.user_id,
    tm.role,
    tm.joined_at,
    u.name AS user_name,
    u.email AS user_email,
    u.avatar_url AS user_avatar_url,
    u.active AS user_active
FROM team_members tm
INNER JOIN users u ON u.id = tm.user_id
WHERE tm.team_id = $1
ORDER BY
    CASE WHEN tm.role = 'TEAM_LEADER' THEN 0 ELSE 1 END,
    u.name ASC
`

type ListTeamMembersRow struct {
	TeamID        int64       `json:"team_id"`
	UserID        int64       `json:"user_id"`
	Role          TeamRole    `json:"role"`
	JoinedAt      time.Time   `json:"joined_at"`
	UserName      string      `json:"user_name"`
	UserEmail     string      `json:"user_email"`
	UserAvatarUrl pgtype.Text `json:"user_avatar_url"`
	UserActive    bool        `json:"user_active"`
}

func (q *Queries) ListTeamMembers(ctx context.Context, teamID int64) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMembersRow
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.TeamID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatarUrl,
			&i.UserActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByOrg = `-- name: ListTeamsByOrg :many
SELECT
    t.id,
    t.public_id,
    t.org_id,
    t.name,
    t.description,
    t.created_by_user,
    t.created_at,
    t.updated_at
FROM teams t
WHERE t.org_id = $1
ORDER BY t.name ASC
`

func (q *Queries) ListTeamsByOrg(ctx context.Context, orgID int64) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.CreatedByUser,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsForUser = `-- name: ListTeamsForUser :many
SELECT
    t.id,
    t.public_id,
    t.org_id,
    t.name,
    t.description,
    t.created_by_user,
    t.created_at,
    t.updated_at,
    tm.role AS my_role
FROM teams t
INNER JOIN team_members tm ON tm.team_id = t.id
WHERE t.org_id = $1
  AND tm.user_id = $2
ORDER BY t.name ASC
`

type ListTeamsForUserParams struct {
	OrgID  int64 `json:"org_id"`
	UserID int64 `json:"user_id"`
}

type ListTeamsForUserRow struct {
	ID            int64       `json:"id"`
	PublicID      uuid.UUID   `json:"public_id"`
	OrgID         int64       `json:"org_id"`
	Name          string      `json:"name"`
	Description   pgtype.Text `json:"description"`
	CreatedByUser int64       `json:"created_by_user"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	MyRole        TeamRole    `json:"my_role"`
}

func (q *Queries) ListTeamsForUser(ctx context.Context, arg ListTeamsForUserParams) ([]ListTeamsForUserRow, error) {
	rows, err := q.db.Query(ctx, listTeamsForUser, arg.OrgID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamsForUserRow
	for rows.Next() {
		var i ListTeamsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.CreatedByUser,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MyRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
DELETE FROM team_members
WHERE team_id = $1
  AND user_id = $2
`

type RemoveTeamMemberParams struct {
	TeamID int64 `json:"team_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	_, err := q.db.Exec(ctx, removeTeamMember, arg.TeamID, arg.UserID)
	return err
}

const updateTeamMemberRole = `-- name: UpdateTeamMemberRole :one
UPDATE team_members
SET role = $3
WHERE team_id = $1
  AND user_id = $2
RETURNING team_id, user_id, role, joined_at
`

type UpdateTeamMemberRoleParams struct {
	TeamID int64    `json:"team_id"`
	UserID int64    `json:"user_id"`
	Role   TeamRole `json:"role"`
}

func (q *Queries) UpdateTeamMemberRole(ctx context.Context, arg UpdateTeamMemberRoleParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, updateTeamMemberRole, arg.TeamID, arg.UserID, arg.Role)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}
