// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (org_id, email, password_hash, name, avatar_url, org_role)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, email, name, org_role, created_at
`

type CreateUserParams struct {
	OrgID        int64       `json:"org_id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Name         string      `json:"name"`
	AvatarUrl    pgtype.Text `json:"avatar_url"`
	OrgRole      OrgRole     `json:"org_role"`
}

type CreateUserRow struct {
	ID        int64     `json:"id"`
	OrgID     int64     `json:"org_id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	OrgRole   OrgRole   `json:"org_role"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.OrgID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.AvatarUrl,
		arg.OrgRole,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Name,
		&i.OrgRole,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, org_id, email, password_hash, name, org_role, active 
FROM users 
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           int64   `json:"id"`
	OrgID        int64   `json:"org_id"`
	Email        string  `json:"email"`
	PasswordHash string  `json:"password_hash"`
	Name         string  `json:"name"`
	OrgRole      OrgRole `json:"org_role"`
	Active       bool    `json:"active"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.OrgRole,
		&i.Active,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, org_id, email, name, org_role, active, avatar_url
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID        int64       `json:"id"`
	OrgID     int64       `json:"org_id"`
	Email     string      `json:"email"`
	Name      string      `json:"name"`
	OrgRole   OrgRole     `json:"org_role"`
	Active    bool        `json:"active"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Name,
		&i.OrgRole,
		&i.Active,
		&i.AvatarUrl,
	)
	return i, err
}

const listUsersByOrg = `-- name: ListUsersByOrg :many
SELECT id, org_id, email, name, org_role, active, avatar_url
FROM users
WHERE org_id = $1
  AND active = true
ORDER BY name ASC
`

type ListUsersByOrgRow struct {
	ID        int64       `json:"id"`
	OrgID     int64       `json:"org_id"`
	Email     string      `json:"email"`
	Name      string      `json:"name"`
	OrgRole   OrgRole     `json:"org_role"`
	Active    bool        `json:"active"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) ListUsersByOrg(ctx context.Context, orgID int64) ([]ListUsersByOrgRow, error) {
	rows, err := q.db.Query(ctx, listUsersByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersByOrgRow
	for rows.Next() {
		var i ListUsersByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Email,
			&i.Name,
			&i.OrgRole,
			&i.Active,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
