// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_tokens.sql

package publicdb

import (
	"context"

	"github.com/google/uuid"
)

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
DELETE FROM public.user_device_tokens
WHERE token = $1
`

func (q *Queries) DeleteDeviceToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteDeviceToken, token)
	return err
}

const getDeviceTokensForUsers = `-- name: GetDeviceTokensForUsers :many
SELECT user_id, token, platform
FROM public.user_device_tokens
WHERE user_id = ANY($1::uuid[])
`

type GetDeviceTokensForUsersRow struct {
	UserID   uuid.UUID `json:"user_id"`
	Token    string    `json:"token"`
	Platform string    `json:"platform"`
}

func (q *Queries) GetDeviceTokensForUsers(ctx context.Context, userIds []uuid.UUID) ([]GetDeviceTokensForUsersRow, error) {
	rows, err := q.db.Query(ctx, getDeviceTokensForUsers, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeviceTokensForUsersRow
	for rows.Next() {
		var i GetDeviceTokensForUsersRow
		if err := rows.Scan(&i.UserID, &i.Token, &i.Platform); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :one
INSERT INTO public.user_device_tokens (user_id, token, platform)
VALUES ($1, $2, $3)
ON CONFLICT (token) DO UPDATE
SET user_id = EXCLUDED.user_id,
    platform = EXCLUDED.platform,
    updated_at = NOW()
RETURNING id, user_id, token, platform, created_at, updated_at
`

type UpsertDeviceTokenParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Token    string    `json:"token"`
	Platform string    `json:"platform"`
}

func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (UserDeviceToken, error) {
	row := q.db.QueryRow(ctx, upsertDeviceToken, arg.UserID, arg.Token, arg.Platform)
	var i UserDeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Platform,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
