// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package publicdb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Org struct {
	ID         int64              `json:"id"`
	PublicID   uuid.UUID          `json:"public_id"`
	Name       string             `json:"name"`
	SchemaName string             `json:"schema_name"`
	CreatedAt  time.Time          `json:"created_at"`
	UpdatedAt  time.Time          `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type OrgUser struct {
	OrgID  int64 `json:"org_id"`
	UserID int64 `json:"user_id"`
}

type User struct {
	ID           int64              `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	DisplayName  string             `json:"display_name"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}
