// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package publicdb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Org struct {
	ID                int64              `json:"id"`
	PublicID          uuid.UUID          `json:"public_id"`
	Name              string             `json:"name"`
	SchemaName        string             `json:"schema_name"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	LifecycleState    string             `json:"lifecycle_state"`
	TenantVersion     int64              `json:"tenant_version"`
	TenantChecksum    string             `json:"tenant_checksum"`
	ReconcileAttempts int32              `json:"reconcile_attempts"`
	NextAttemptAt     time.Time          `json:"next_attempt_at"`
	LastErrorCode     pgtype.Text        `json:"last_error_code"`
	LastErrorDetail   pgtype.Text        `json:"last_error_detail"`
	LastAttemptAt     pgtype.Timestamptz `json:"last_attempt_at"`
	ProvisionedAt     pgtype.Timestamptz `json:"provisioned_at"`
}

type OrgUser struct {
	OrgID  int64 `json:"org_id"`
	UserID int64 `json:"user_id"`
}

type User struct {
	ID             int64              `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Email          string             `json:"email"`
	PasswordHash   string             `json:"password_hash"`
	DisplayName    string             `json:"display_name"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	EmailCanonical string             `json:"email_canonical"`
}
