// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: org_user.sql

package publicdb

import (
	"context"
)

const addUserToOrg = `-- name: AddUserToOrg :one
INSERT INTO public.org_user (org_id, user_id)
VALUES ($1, $2)
RETURNING org_id, user_id
`

type AddUserToOrgParams struct {
	OrgID  int64 `json:"org_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) AddUserToOrg(ctx context.Context, arg AddUserToOrgParams) (OrgUser, error) {
	row := q.db.QueryRow(ctx, addUserToOrg, arg.OrgID, arg.UserID)
	var i OrgUser
	err := row.Scan(&i.OrgID, &i.UserID)
	return i, err
}

const getNumberOfUsersInOrg = `-- name: GetNumberOfUsersInOrg :one
SELECT COUNT(*)
FROM public.org_user
WHERE org_id = $1
`

func (q *Queries) GetNumberOfUsersInOrg(ctx context.Context, orgID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getNumberOfUsersInOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOrgsForUser = `-- name: GetOrgsForUser :many
SELECT o.id, o.public_id, o.name, o.schema_name, o.created_at, o.updated_at, o.deleted_at,
       o.lifecycle_state, o.tenant_version,
       o.tenant_checksum, o.reconcile_attempts, o.next_attempt_at, o.last_error_code,
       o.last_error_detail, o.last_attempt_at, o.provisioned_at
FROM public.orgs AS o
JOIN public.org_user AS ou ON o.id = ou.org_id
WHERE ou.user_id = $1
AND o.deleted_at IS NULL
ORDER BY o.name ASC, o.id ASC
LIMIT $2
`

type GetOrgsForUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) GetOrgsForUser(ctx context.Context, arg GetOrgsForUserParams) ([]Org, error) {
	rows, err := q.db.Query(ctx, getOrgsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Org
	for rows.Next() {
		var i Org
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Name,
			&i.SchemaName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LifecycleState,
			&i.TenantVersion,
			&i.TenantChecksum,
			&i.ReconcileAttempts,
			&i.NextAttemptAt,
			&i.LastErrorCode,
			&i.LastErrorDetail,
			&i.LastAttemptAt,
			&i.ProvisionedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersInOrg = `-- name: GetUsersInOrg :many
SELECT u.id, u.user_id, u.email, u.password_hash, u.display_name, u.created_at, u.updated_at, u.deleted_at, u.email_canonical, u.password_normalization
FROM public.users AS u
JOIN public.org_user AS ou ON u.id = ou.user_id
WHERE ou.org_id = $1
AND u.deleted_at IS NULL
ORDER BY u.created_at ASC, u.id ASC
LIMIT $2
`

type GetUsersInOrgParams struct {
	OrgID int64 `json:"org_id"`
	Limit int32 `json:"limit"`
}

func (q *Queries) GetUsersInOrg(ctx context.Context, arg GetUsersInOrgParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersInOrg, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.PasswordHash,
			&i.DisplayName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.EmailCanonical,
			&i.PasswordNormalization,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromOrg = `-- name: RemoveUserFromOrg :one
DELETE FROM public.org_user
WHERE org_id = $1
AND user_id = $2
RETURNING org_id, user_id
`

type RemoveUserFromOrgParams struct {
	OrgID  int64 `json:"org_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) RemoveUserFromOrg(ctx context.Context, arg RemoveUserFromOrgParams) (OrgUser, error) {
	row := q.db.QueryRow(ctx, removeUserFromOrg, arg.OrgID, arg.UserID)
	var i OrgUser
	err := row.Scan(&i.OrgID, &i.UserID)
	return i, err
}
