// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization_invitations.sql

package publicdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acceptOrganizationInvitation = `-- name: AcceptOrganizationInvitation :one
WITH consumed AS (
    DELETE FROM public.organization_invitations
    WHERE id = $1
    RETURNING org_id
), added AS (
    INSERT INTO public.org_user (org_id, user_id, role)
    SELECT consumed.org_id, $2, 'member'
    FROM consumed
    ON CONFLICT (org_id, user_id) DO NOTHING
    RETURNING org_id
)
SELECT consumed.org_id FROM consumed
`

type AcceptOrganizationInvitationParams struct {
	InvitationID int64 `json:"invitation_id"`
	UserID       int64 `json:"user_id"`
}

func (q *Queries) AcceptOrganizationInvitation(ctx context.Context, arg AcceptOrganizationInvitationParams) (int64, error) {
	row := q.db.QueryRow(ctx, acceptOrganizationInvitation, arg.InvitationID, arg.UserID)
	var org_id int64
	err := row.Scan(&org_id)
	return org_id, err
}

const createOrganizationInvitation = `-- name: CreateOrganizationInvitation :one
INSERT INTO public.organization_invitations (org_id, email_hmac, token_hash, expires_at)
VALUES ($1, $2, $3, now() + interval '7 days')
RETURNING id, public_id, org_id, email_hmac, token_hash, created_at, expires_at
`

type CreateOrganizationInvitationParams struct {
	OrgID     int64  `json:"org_id"`
	EmailHmac []byte `json:"email_hmac"`
	TokenHash []byte `json:"token_hash"`
}

func (q *Queries) CreateOrganizationInvitation(ctx context.Context, arg CreateOrganizationInvitationParams) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, createOrganizationInvitation, arg.OrgID, arg.EmailHmac, arg.TokenHash)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.EmailHmac,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const declineOrganizationInvitation = `-- name: DeclineOrganizationInvitation :one
DELETE FROM public.organization_invitations
WHERE id = $1
RETURNING public_id
`

func (q *Queries) DeclineOrganizationInvitation(ctx context.Context, invitationID int64) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, declineOrganizationInvitation, invitationID)
	var public_id uuid.UUID
	err := row.Scan(&public_id)
	return public_id, err
}

const deleteOrganizationInvitation = `-- name: DeleteOrganizationInvitation :one
DELETE FROM public.organization_invitations
WHERE public_id = $1 AND org_id = $2
RETURNING public_id
`

type DeleteOrganizationInvitationParams struct {
	PublicID uuid.UUID `json:"public_id"`
	OrgID    int64     `json:"org_id"`
}

func (q *Queries) DeleteOrganizationInvitation(ctx context.Context, arg DeleteOrganizationInvitationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteOrganizationInvitation, arg.PublicID, arg.OrgID)
	var public_id uuid.UUID
	err := row.Scan(&public_id)
	return public_id, err
}

const getActiveUserInvitationIdentity = `-- name: GetActiveUserInvitationIdentity :one
SELECT id, email_canonical
FROM public.users
WHERE user_id = $1 AND deleted_at IS NULL
`

type GetActiveUserInvitationIdentityRow struct {
	ID             int64  `json:"id"`
	EmailCanonical string `json:"email_canonical"`
}

func (q *Queries) GetActiveUserInvitationIdentity(ctx context.Context, userPublicID uuid.UUID) (GetActiveUserInvitationIdentityRow, error) {
	row := q.db.QueryRow(ctx, getActiveUserInvitationIdentity, userPublicID)
	var i GetActiveUserInvitationIdentityRow
	err := row.Scan(&i.ID, &i.EmailCanonical)
	return i, err
}

const getOrganizationInvitationByTokenHash = `-- name: GetOrganizationInvitationByTokenHash :one
SELECT invitation.id, invitation.public_id, invitation.org_id, invitation.email_hmac,
       invitation.created_at, invitation.expires_at, organization.public_id AS organization_public_id,
       organization.name AS organization_name
FROM public.organization_invitations AS invitation
JOIN public.orgs AS organization ON organization.id = invitation.org_id
WHERE invitation.token_hash = $1
  AND invitation.expires_at > now()
  AND organization.deleted_at IS NULL
  AND organization.lifecycle_state = 'active'
FOR UPDATE OF invitation
`

type GetOrganizationInvitationByTokenHashRow struct {
	ID                   int64     `json:"id"`
	PublicID             uuid.UUID `json:"public_id"`
	OrgID                int64     `json:"org_id"`
	EmailHmac            []byte    `json:"email_hmac"`
	CreatedAt            time.Time `json:"created_at"`
	ExpiresAt            time.Time `json:"expires_at"`
	OrganizationPublicID uuid.UUID `json:"organization_public_id"`
	OrganizationName     string    `json:"organization_name"`
}

func (q *Queries) GetOrganizationInvitationByTokenHash(ctx context.Context, tokenHash []byte) (GetOrganizationInvitationByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationInvitationByTokenHash, tokenHash)
	var i GetOrganizationInvitationByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.EmailHmac,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.OrganizationPublicID,
		&i.OrganizationName,
	)
	return i, err
}

const listOrganizationInvitationsAfter = `-- name: ListOrganizationInvitationsAfter :many
SELECT invitation.id, invitation.public_id, invitation.org_id, invitation.created_at, invitation.expires_at
FROM public.organization_invitations AS invitation
WHERE invitation.org_id = $1
  AND invitation.expires_at > now()
  AND (invitation.created_at, invitation.public_id) >
      ($2, $3::uuid)
ORDER BY invitation.created_at, invitation.public_id
LIMIT $4
`

type ListOrganizationInvitationsAfterParams struct {
	OrgID          int64     `json:"org_id"`
	AfterCreatedAt time.Time `json:"after_created_at"`
	AfterPublicID  uuid.UUID `json:"after_public_id"`
	Limit          int32     `json:"limit"`
}

type ListOrganizationInvitationsAfterRow struct {
	ID        int64     `json:"id"`
	PublicID  uuid.UUID `json:"public_id"`
	OrgID     int64     `json:"org_id"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) ListOrganizationInvitationsAfter(ctx context.Context, arg ListOrganizationInvitationsAfterParams) ([]ListOrganizationInvitationsAfterRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationInvitationsAfter,
		arg.OrgID,
		arg.AfterCreatedAt,
		arg.AfterPublicID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganizationInvitationsAfterRow
	for rows.Next() {
		var i ListOrganizationInvitationsAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrgID,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOrganizationInvitationAdminContext = `-- name: LockOrganizationInvitationAdminContext :one
SELECT organization.id AS org_id, membership.role, organization.lifecycle_state,
       (SELECT count(*) FROM public.org_user AS owners
        WHERE owners.org_id = organization.id AND owners.role = 'owner') AS owner_count
FROM public.orgs AS organization
JOIN public.org_user AS membership ON membership.org_id = organization.id
JOIN public.users AS actor ON actor.id = membership.user_id
WHERE organization.public_id = $1
  AND organization.deleted_at IS NULL
  AND actor.user_id = $2
  AND actor.deleted_at IS NULL
FOR UPDATE OF organization, membership
`

type LockOrganizationInvitationAdminContextParams struct {
	OrganizationPublicID uuid.UUID `json:"organization_public_id"`
	UserPublicID         uuid.UUID `json:"user_public_id"`
}

type LockOrganizationInvitationAdminContextRow struct {
	OrgID          int64  `json:"org_id"`
	Role           string `json:"role"`
	LifecycleState string `json:"lifecycle_state"`
	OwnerCount     int64  `json:"owner_count"`
}

func (q *Queries) LockOrganizationInvitationAdminContext(ctx context.Context, arg LockOrganizationInvitationAdminContextParams) (LockOrganizationInvitationAdminContextRow, error) {
	row := q.db.QueryRow(ctx, lockOrganizationInvitationAdminContext, arg.OrganizationPublicID, arg.UserPublicID)
	var i LockOrganizationInvitationAdminContextRow
	err := row.Scan(
		&i.OrgID,
		&i.Role,
		&i.LifecycleState,
		&i.OwnerCount,
	)
	return i, err
}

const purgeExpiredOrganizationInvitations = `-- name: PurgeExpiredOrganizationInvitations :execrows
WITH expired AS (
    SELECT id FROM public.organization_invitations
    WHERE expires_at <= now()
    ORDER BY expires_at
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
DELETE FROM public.organization_invitations AS invitation
USING expired WHERE invitation.id = expired.id
`

func (q *Queries) PurgeExpiredOrganizationInvitations(ctx context.Context, limit int32) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredOrganizationInvitations, limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
