// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orgs.sql

package publicdb

import (
	"context"

	"github.com/google/uuid"
)

const createOrg = `-- name: CreateOrg :one
INSERT INTO public.orgs (name, public_id, schema_name)
VALUES ($1, $2, $3)
RETURNING id, public_id, name, schema_name, created_at, updated_at, deleted_at
`

type CreateOrgParams struct {
	Name       string    `json:"name"`
	PublicID   uuid.UUID `json:"public_id"`
	SchemaName string    `json:"schema_name"`
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, createOrg, arg.Name, arg.PublicID, arg.SchemaName)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.SchemaName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrgID = `-- name: GetOrgID :one
SELECT id
FROM public.orgs
WHERE public_id = $1
AND deleted_at IS NULL
`

func (q *Queries) GetOrgID(ctx context.Context, publicID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getOrgID, publicID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getOrgName = `-- name: GetOrgName :one
SELECT id, public_id, name, schema_name, created_at, updated_at, deleted_at
FROM public.orgs
WHERE id = $1
AND deleted_at IS NULL
`

func (q *Queries) GetOrgName(ctx context.Context, id int64) (Org, error) {
	row := q.db.QueryRow(ctx, getOrgName, id)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.SchemaName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrgs = `-- name: GetOrgs :many
SELECT id, public_id, name, schema_name, created_at, updated_at, deleted_at
FROM public.orgs
WHERE deleted_at IS NULL
ORDER BY name ASC, id ASC
LIMIT $1
`

func (q *Queries) GetOrgs(ctx context.Context, limit int32) ([]Org, error) {
	rows, err := q.db.Query(ctx, getOrgs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Org
	for rows.Next() {
		var i Org
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Name,
			&i.SchemaName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSchemaFromID = `-- name: GetSchemaFromID :one
SELECT schema_name
FROM public.orgs
WHERE id = $1
`

func (q *Queries) GetSchemaFromID(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, getSchemaFromID, id)
	var schema_name string
	err := row.Scan(&schema_name)
	return schema_name, err
}

const restoreOrg = `-- name: RestoreOrg :one
UPDATE public.orgs
SET deleted_at = NULL, updated_at = NOW()
WHERE public_id = $1
AND deleted_at IS NOT NULL
RETURNING id, public_id, name, schema_name, created_at, updated_at, deleted_at
`

func (q *Queries) RestoreOrg(ctx context.Context, publicID uuid.UUID) (Org, error) {
	row := q.db.QueryRow(ctx, restoreOrg, publicID)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.SchemaName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteOrg = `-- name: SoftDeleteOrg :one
UPDATE public.orgs
SET deleted_at = NOW(), updated_at = NOW()
WHERE public_id = $1
AND deleted_at IS NULL
RETURNING id, public_id, name, schema_name, created_at, updated_at, deleted_at
`

func (q *Queries) SoftDeleteOrg(ctx context.Context, publicID uuid.UUID) (Org, error) {
	row := q.db.QueryRow(ctx, softDeleteOrg, publicID)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.SchemaName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateOrg = `-- name: UpdateOrg :one
UPDATE public.orgs
SET name = $2, updated_at = NOW()
WHERE public_id = $1
AND deleted_at IS NULL
RETURNING id, public_id, name, schema_name, created_at, updated_at, deleted_at
`

type UpdateOrgParams struct {
	PublicID uuid.UUID `json:"public_id"`
	Name     string    `json:"name"`
}

func (q *Queries) UpdateOrg(ctx context.Context, arg UpdateOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, updateOrg, arg.PublicID, arg.Name)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.SchemaName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
