// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package publicdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO public.sessions (
    user_id, token_hash, user_agent, created_at, last_seen_at, absolute_expires_at
)
SELECT u.id, $1, $2, $3,
       $3, $4
FROM public.users u
WHERE u.user_id = $5 AND u.deleted_at IS NULL
RETURNING id, session_id, user_id, token_hash, user_agent, created_at,
          last_seen_at, absolute_expires_at, revoked_at
`

type CreateSessionParams struct {
	TokenHash         []byte    `json:"token_hash"`
	UserAgent         string    `json:"user_agent"`
	Now               time.Time `json:"now"`
	AbsoluteExpiresAt time.Time `json:"absolute_expires_at"`
	UserPublicID      uuid.UUID `json:"user_public_id"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.TokenHash,
		arg.UserAgent,
		arg.Now,
		arg.AbsoluteExpiresAt,
		arg.UserPublicID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteAbsoluteExpiredSessions = `-- name: DeleteAbsoluteExpiredSessions :execrows
WITH candidates AS (
    SELECT candidate_sessions.id FROM public.sessions candidate_sessions
    WHERE candidate_sessions.revoked_at IS NULL
      AND candidate_sessions.absolute_expires_at <= $1
    ORDER BY candidate_sessions.absolute_expires_at, candidate_sessions.id
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
DELETE FROM public.sessions s USING candidates c WHERE s.id = c.id
`

type DeleteAbsoluteExpiredSessionsParams struct {
	Now        time.Time `json:"now"`
	BatchLimit int32     `json:"batch_limit"`
}

func (q *Queries) DeleteAbsoluteExpiredSessions(ctx context.Context, arg DeleteAbsoluteExpiredSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAbsoluteExpiredSessions, arg.Now, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteIdleExpiredSessions = `-- name: DeleteIdleExpiredSessions :execrows
WITH candidates AS (
    SELECT candidate_sessions.id FROM public.sessions candidate_sessions
    WHERE candidate_sessions.revoked_at IS NULL
      AND candidate_sessions.absolute_expires_at > $1
      AND candidate_sessions.last_seen_at <= $2
    ORDER BY candidate_sessions.last_seen_at, candidate_sessions.id
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
DELETE FROM public.sessions s USING candidates c WHERE s.id = c.id
`

type DeleteIdleExpiredSessionsParams struct {
	Now        time.Time `json:"now"`
	IdleCutoff time.Time `json:"idle_cutoff"`
	BatchLimit int32     `json:"batch_limit"`
}

func (q *Queries) DeleteIdleExpiredSessions(ctx context.Context, arg DeleteIdleExpiredSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIdleExpiredSessions, arg.Now, arg.IdleCutoff, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRevokedSessions = `-- name: DeleteRevokedSessions :execrows
WITH candidates AS (
    SELECT candidate_sessions.id FROM public.sessions candidate_sessions
    WHERE candidate_sessions.revoked_at IS NOT NULL
    ORDER BY candidate_sessions.revoked_at, candidate_sessions.id
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
DELETE FROM public.sessions s USING candidates c WHERE s.id = c.id
`

func (q *Queries) DeleteRevokedSessions(ctx context.Context, batchLimit int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRevokedSessions, batchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT s.id, s.session_id, s.user_id, s.token_hash, s.user_agent, s.created_at,
       s.last_seen_at, s.absolute_expires_at, s.revoked_at,
       u.user_id AS user_public_id, u.email, u.display_name
FROM public.sessions s
JOIN public.users u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.revoked_at IS NULL
  AND s.absolute_expires_at > $2
  AND s.last_seen_at > $3
  AND u.deleted_at IS NULL
`

type GetSessionByTokenHashParams struct {
	TokenHash  []byte    `json:"token_hash"`
	Now        time.Time `json:"now"`
	IdleCutoff time.Time `json:"idle_cutoff"`
}

type GetSessionByTokenHashRow struct {
	ID                int64              `json:"id"`
	SessionID         uuid.UUID          `json:"session_id"`
	UserID            int64              `json:"user_id"`
	TokenHash         []byte             `json:"token_hash"`
	UserAgent         string             `json:"user_agent"`
	CreatedAt         time.Time          `json:"created_at"`
	LastSeenAt        time.Time          `json:"last_seen_at"`
	AbsoluteExpiresAt time.Time          `json:"absolute_expires_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	UserPublicID      uuid.UUID          `json:"user_public_id"`
	Email             string             `json:"email"`
	DisplayName       string             `json:"display_name"`
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, arg GetSessionByTokenHashParams) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, arg.TokenHash, arg.Now, arg.IdleCutoff)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.UserPublicID,
		&i.Email,
		&i.DisplayName,
	)
	return i, err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT s.session_id, s.user_agent, s.created_at, s.last_seen_at,
       s.absolute_expires_at, s.revoked_at
FROM public.sessions s
JOIN public.users u ON u.id = s.user_id
WHERE u.user_id = $1
  AND s.revoked_at IS NULL
  AND s.absolute_expires_at > $2
  AND s.last_seen_at > $3
ORDER BY s.created_at DESC, s.id DESC
LIMIT $4
`

type ListUserSessionsParams struct {
	UserPublicID uuid.UUID `json:"user_public_id"`
	Now          time.Time `json:"now"`
	IdleCutoff   time.Time `json:"idle_cutoff"`
	ResultLimit  int32     `json:"result_limit"`
}

type ListUserSessionsRow struct {
	SessionID         uuid.UUID          `json:"session_id"`
	UserAgent         string             `json:"user_agent"`
	CreatedAt         time.Time          `json:"created_at"`
	LastSeenAt        time.Time          `json:"last_seen_at"`
	AbsoluteExpiresAt time.Time          `json:"absolute_expires_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) ListUserSessions(ctx context.Context, arg ListUserSessionsParams) ([]ListUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, listUserSessions,
		arg.UserPublicID,
		arg.Now,
		arg.IdleCutoff,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserSessionsRow
	for rows.Next() {
		var i ListUserSessionsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.AbsoluteExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE public.sessions s
SET revoked_at = COALESCE(s.revoked_at, $1)
FROM public.users u
WHERE s.user_id = u.id AND u.user_id = $2
`

type RevokeAllUserSessionsParams struct {
	Now          pgtype.Timestamptz `json:"now"`
	UserPublicID uuid.UUID          `json:"user_public_id"`
}

func (q *Queries) RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, arg.Now, arg.UserPublicID)
	return err
}

const revokeSessionByHash = `-- name: RevokeSessionByHash :execrows
UPDATE public.sessions
SET revoked_at = COALESCE(revoked_at, $1)
WHERE token_hash = $2
`

type RevokeSessionByHashParams struct {
	Now       pgtype.Timestamptz `json:"now"`
	TokenHash []byte             `json:"token_hash"`
}

func (q *Queries) RevokeSessionByHash(ctx context.Context, arg RevokeSessionByHashParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionByHash, arg.Now, arg.TokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserSession = `-- name: RevokeUserSession :execrows
UPDATE public.sessions s
SET revoked_at = COALESCE(s.revoked_at, $1)
FROM public.users u
WHERE s.user_id = u.id
  AND u.user_id = $2
  AND s.session_id = $3
`

type RevokeUserSessionParams struct {
	Now             pgtype.Timestamptz `json:"now"`
	UserPublicID    uuid.UUID          `json:"user_public_id"`
	SessionPublicID uuid.UUID          `json:"session_public_id"`
}

func (q *Queries) RevokeUserSession(ctx context.Context, arg RevokeUserSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserSession, arg.Now, arg.UserPublicID, arg.SessionPublicID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchSession = `-- name: TouchSession :execrows
UPDATE public.sessions
SET last_seen_at = $1
WHERE token_hash = $2
  AND revoked_at IS NULL
  AND absolute_expires_at > $1
  AND last_seen_at > $3
  AND last_seen_at <= $4
`

type TouchSessionParams struct {
	Now         time.Time `json:"now"`
	TokenHash   []byte    `json:"token_hash"`
	IdleCutoff  time.Time `json:"idle_cutoff"`
	TouchBefore time.Time `json:"touch_before"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchSession,
		arg.Now,
		arg.TokenHash,
		arg.IdleCutoff,
		arg.TouchBefore,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
