// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenancy.sql

package publicdb

import (
	"context"

	"github.com/google/uuid"
)

const resolveOrganizationContext = `-- name: ResolveOrganizationContext :one
SELECT organization.id AS organization_id,
       organization.public_id AS organization_public_id,
       organization.schema_name,
       organization.lifecycle_state,
       organization.tenant_version,
       organization.tenant_checksum,
       app_user.id AS user_id,
       app_user.user_id AS user_public_id,
       membership.role AS organization_role,
       (namespace.oid IS NOT NULL)::boolean AS schema_exists
FROM public.users AS app_user
JOIN public.org_user AS membership ON membership.user_id = app_user.id
JOIN public.orgs AS organization ON organization.id = membership.org_id
LEFT JOIN pg_catalog.pg_namespace AS namespace ON namespace.nspname = organization.schema_name
WHERE app_user.user_id = $1
  AND app_user.deleted_at IS NULL
  AND organization.public_id = $2
  AND organization.deleted_at IS NULL
`

type ResolveOrganizationContextParams struct {
	UserPublicID         uuid.UUID `json:"user_public_id"`
	OrganizationPublicID uuid.UUID `json:"organization_public_id"`
}

type ResolveOrganizationContextRow struct {
	OrganizationID       int64     `json:"organization_id"`
	OrganizationPublicID uuid.UUID `json:"organization_public_id"`
	SchemaName           string    `json:"schema_name"`
	LifecycleState       string    `json:"lifecycle_state"`
	TenantVersion        int64     `json:"tenant_version"`
	TenantChecksum       string    `json:"tenant_checksum"`
	UserID               int64     `json:"user_id"`
	UserPublicID         uuid.UUID `json:"user_public_id"`
	OrganizationRole     string    `json:"organization_role"`
	SchemaExists         bool      `json:"schema_exists"`
}

func (q *Queries) ResolveOrganizationContext(ctx context.Context, arg ResolveOrganizationContextParams) (ResolveOrganizationContextRow, error) {
	row := q.db.QueryRow(ctx, resolveOrganizationContext, arg.UserPublicID, arg.OrganizationPublicID)
	var i ResolveOrganizationContextRow
	err := row.Scan(
		&i.OrganizationID,
		&i.OrganizationPublicID,
		&i.SchemaName,
		&i.LifecycleState,
		&i.TenantVersion,
		&i.TenantChecksum,
		&i.UserID,
		&i.UserPublicID,
		&i.OrganizationRole,
		&i.SchemaExists,
	)
	return i, err
}
