// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_public_keys.sql

package publicdb

import (
	"context"

	"github.com/google/uuid"
)

const getUserPublicKey = `-- name: GetUserPublicKey :one
SELECT user_id, public_key, created_at
FROM public.user_public_keys
WHERE user_id = $1
`

func (q *Queries) GetUserPublicKey(ctx context.Context, userID uuid.UUID) (UserPublicKey, error) {
	row := q.db.QueryRow(ctx, getUserPublicKey, userID)
	var i UserPublicKey
	err := row.Scan(&i.UserID, &i.PublicKey, &i.CreatedAt)
	return i, err
}

const getUserPublicKeys = `-- name: GetUserPublicKeys :many
SELECT user_id, public_key, created_at
FROM public.user_public_keys
WHERE user_id = ANY($1::uuid[])
ORDER BY user_id
LIMIT $2
`

type GetUserPublicKeysParams struct {
	UserIds []uuid.UUID `json:"user_ids"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) GetUserPublicKeys(ctx context.Context, arg GetUserPublicKeysParams) ([]UserPublicKey, error) {
	rows, err := q.db.Query(ctx, getUserPublicKeys, arg.UserIds, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserPublicKey
	for rows.Next() {
		var i UserPublicKey
		if err := rows.Scan(&i.UserID, &i.PublicKey, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserPublicKey = `-- name: UpsertUserPublicKey :one
INSERT INTO public.user_public_keys (user_id, public_key)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE
SET public_key = EXCLUDED.public_key, created_at = NOW()
RETURNING user_id, public_key, created_at
`

type UpsertUserPublicKeyParams struct {
	UserID    uuid.UUID `json:"user_id"`
	PublicKey string    `json:"public_key"`
}

func (q *Queries) UpsertUserPublicKey(ctx context.Context, arg UpsertUserPublicKeyParams) (UserPublicKey, error) {
	row := q.db.QueryRow(ctx, upsertUserPublicKey, arg.UserID, arg.PublicKey)
	var i UserPublicKey
	err := row.Scan(&i.UserID, &i.PublicKey, &i.CreatedAt)
	return i, err
}
