// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_public_keys.sql

package publicdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUserPublicKey = `-- name: GetUserPublicKey :one
SELECT user_id, public_key, encrypted_private_key, kek_salt, kek_iterations, kek_algorithm, created_at, updated_at
FROM public.user_public_keys
WHERE user_id = $1
`

type GetUserPublicKeyRow struct {
	UserID              uuid.UUID   `json:"user_id"`
	PublicKey           string      `json:"public_key"`
	EncryptedPrivateKey pgtype.Text `json:"encrypted_private_key"`
	KekSalt             pgtype.Text `json:"kek_salt"`
	KekIterations       pgtype.Int4 `json:"kek_iterations"`
	KekAlgorithm        string      `json:"kek_algorithm"`
	CreatedAt           time.Time   `json:"created_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
}

func (q *Queries) GetUserPublicKey(ctx context.Context, userID uuid.UUID) (GetUserPublicKeyRow, error) {
	row := q.db.QueryRow(ctx, getUserPublicKey, userID)
	var i GetUserPublicKeyRow
	err := row.Scan(
		&i.UserID,
		&i.PublicKey,
		&i.EncryptedPrivateKey,
		&i.KekSalt,
		&i.KekIterations,
		&i.KekAlgorithm,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPublicKeys = `-- name: GetUserPublicKeys :many
SELECT user_id, public_key, created_at
FROM public.user_public_keys
WHERE user_id = ANY($1::uuid[])
ORDER BY user_id
LIMIT $2
`

type GetUserPublicKeysParams struct {
	UserIds []uuid.UUID `json:"user_ids"`
	Limit   int32       `json:"limit"`
}

type GetUserPublicKeysRow struct {
	UserID    uuid.UUID `json:"user_id"`
	PublicKey string    `json:"public_key"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetUserPublicKeys(ctx context.Context, arg GetUserPublicKeysParams) ([]GetUserPublicKeysRow, error) {
	rows, err := q.db.Query(ctx, getUserPublicKeys, arg.UserIds, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserPublicKeysRow
	for rows.Next() {
		var i GetUserPublicKeysRow
		if err := rows.Scan(&i.UserID, &i.PublicKey, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserKeys = `-- name: UpsertUserKeys :one
INSERT INTO public.user_public_keys (user_id, public_key, encrypted_private_key, kek_salt, kek_iterations, kek_algorithm)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id) DO UPDATE
SET public_key = EXCLUDED.public_key,
    encrypted_private_key = COALESCE(EXCLUDED.encrypted_private_key, user_public_keys.encrypted_private_key),
    kek_salt = COALESCE(EXCLUDED.kek_salt, user_public_keys.kek_salt),
    kek_iterations = COALESCE(EXCLUDED.kek_iterations, user_public_keys.kek_iterations),
    kek_algorithm = COALESCE(EXCLUDED.kek_algorithm, user_public_keys.kek_algorithm),
    updated_at = NOW()
RETURNING user_id, public_key, encrypted_private_key, kek_salt, kek_iterations, kek_algorithm, created_at, updated_at
`

type UpsertUserKeysParams struct {
	UserID              uuid.UUID   `json:"user_id"`
	PublicKey           string      `json:"public_key"`
	EncryptedPrivateKey pgtype.Text `json:"encrypted_private_key"`
	KekSalt             pgtype.Text `json:"kek_salt"`
	KekIterations       pgtype.Int4 `json:"kek_iterations"`
	KekAlgorithm        string      `json:"kek_algorithm"`
}

type UpsertUserKeysRow struct {
	UserID              uuid.UUID   `json:"user_id"`
	PublicKey           string      `json:"public_key"`
	EncryptedPrivateKey pgtype.Text `json:"encrypted_private_key"`
	KekSalt             pgtype.Text `json:"kek_salt"`
	KekIterations       pgtype.Int4 `json:"kek_iterations"`
	KekAlgorithm        string      `json:"kek_algorithm"`
	CreatedAt           time.Time   `json:"created_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
}

func (q *Queries) UpsertUserKeys(ctx context.Context, arg UpsertUserKeysParams) (UpsertUserKeysRow, error) {
	row := q.db.QueryRow(ctx, upsertUserKeys,
		arg.UserID,
		arg.PublicKey,
		arg.EncryptedPrivateKey,
		arg.KekSalt,
		arg.KekIterations,
		arg.KekAlgorithm,
	)
	var i UpsertUserKeysRow
	err := row.Scan(
		&i.UserID,
		&i.PublicKey,
		&i.EncryptedPrivateKey,
		&i.KekSalt,
		&i.KekIterations,
		&i.KekAlgorithm,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
