CREATE TABLE public.sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT sessions_pk PRIMARY KEY,
    session_id UUID NOT NULL DEFAULT gen_random_uuid()
        CONSTRAINT sessions_session_id_unique UNIQUE,
    user_id BIGINT NOT NULL
        CONSTRAINT sessions_user_fk REFERENCES public.users (id) ON DELETE CASCADE,
    token_hash BYTEA NOT NULL
        CONSTRAINT sessions_token_hash_unique UNIQUE,
    user_agent TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,
    absolute_expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    CONSTRAINT sessions_token_hash_length CHECK (octet_length(token_hash) = 32),
    CONSTRAINT sessions_user_agent_length CHECK (octet_length(user_agent) <= 256),
    CONSTRAINT sessions_time_order CHECK (
        last_seen_at >= created_at AND absolute_expires_at > created_at
    ),
    CONSTRAINT sessions_revoked_after_creation CHECK (
        revoked_at IS NULL OR revoked_at >= created_at
    )
);

CREATE INDEX sessions_user_created_idx
    ON public.sessions (user_id, created_at DESC, id DESC);
CREATE INDEX sessions_revoked_cleanup_idx
    ON public.sessions (revoked_at, id) WHERE revoked_at IS NOT NULL;
CREATE INDEX sessions_absolute_cleanup_idx
    ON public.sessions (absolute_expires_at, id) WHERE revoked_at IS NULL;
CREATE INDEX sessions_idle_cleanup_idx
    ON public.sessions (last_seen_at, id) WHERE revoked_at IS NULL;

ALTER TABLE public.sessions OWNER TO synodus_owner;
ALTER SEQUENCE public.sessions_id_seq OWNER TO synodus_owner;
REVOKE ALL ON public.sessions FROM synodus_runtime;
REVOKE ALL ON public.sessions_id_seq FROM synodus_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.sessions TO synodus_runtime;
GRANT USAGE, SELECT ON public.sessions_id_seq TO synodus_runtime;
