CREATE TABLE orgs (
    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT orgs_pk PRIMARY KEY,

    public_id UUID NOT NULL DEFAULT gen_random_uuid()
        CONSTRAINT orgs_public_id_unique UNIQUE,

    name VARCHAR(255) NOT NULL,

    schema_name VARCHAR(255) NOT NULL
        CONSTRAINT orgs_schema_name_unique UNIQUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    deleted_at TIMESTAMPTZ DEFAULT NULL
);