CREATE TABLE users (
    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT users_pk PRIMARY KEY,

    user_id UUID NOT NULL DEFAULT gen_random_uuid()
        CONSTRAINT users_user_id_unique UNIQUE,
    email VARCHAR(255) NOT NULL
        CONSTRAINT users_email_unique UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);